Repository MichaIng/DietPi-Docs, pull requests merged in 2020-10, with the labels that each got.

#61 File DietPi-Docs_Todo.md added
  DietPi-Docs_Todo.md
Labels: documentation

#117 Simplify link checks
  .github/workflows/actions.yml
  README.md
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/remote_desktop.md
  docs/user-guide_installation.md
Labels: enhancement

#145 Finished chapter WiFi HotSpot (fixes #140)
  .wordlist.txt
  docs/assets/images/dietpi-software-wifihotspot-torhotspot.png
  docs/assets/images/dietpi-software-wifihotspot-wifihotspot.png
  docs/dietpi_optimised_software.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/printing.md
  docs/software/ssh.md
  docs/software/wifi_hotspot.md
Labels: documentation

#148 Porting of Remote desktop access
  .wordlist.txt
  docs/assets/images/dietpi-software-remotedesktop-nomachine.png
  docs/assets/images/dietpi-software-remotedesktop-realvnc.png
  docs/assets/images/dietpi-software-remotedesktop-remot3it.png
  docs/assets/images/dietpi-software-remotedesktop-virtualhere.png
  docs/assets/images/dietpi-software-remotedesktop-xrdp.png
  docs/dietpi_optimised_software.md
  docs/software/remote_desktop.md
Labels: documentation

#149 Porting System Security
  docs/assets/images/dietpi-software-security-docker1.svg
  docs/assets/images/dietpi-software-security-docker2.svg
  docs/assets/images/dietpi-software-security-fail2ban1.jpg
  docs/assets/images/dietpi-software-security-fail2ban2.jpg
  docs/dietpi_docs_todo.md
  docs/dietpi_optimised_software.md
  docs/software/system_security.md
Labels: documentation

#161 Linking a description of Pi-hole in combination with Netdata
  docs/assets/images/dietpi-software-camera-motioneye.png
  docs/assets/images/dietpi-software-camera-rpicamcontrol.png
  docs/dietpi_optimised_software.md
  docs/software/camera.md
  docs/software/dns_servers.md
  docs/software/system_stats.md
Labels: documentation

#162 Shortening tab text
  docs/software/dns_servers.md
  docs/software/system_stats.md
Labels: documentation

#164 Porting of vpn.md
  .wordlist.txt
  docs/software/vpn.md
Labels: documentation

#172 Fix ASUS Tinker Board link
  .github/workflows/actions.yml
  docs/dietpi_sbc.md
Labels: bug

#177 Housekeeping as of dietpi_docs_todo.md and porting of gaming.md
  .wordlist.txt
  docs/assets/images/dietpi-software-games-amiberry.jpg
  docs/assets/images/dietpi-software-games-cuberite.png
  docs/assets/images/dietpi-software-games-dxxrebirth.png
  docs/assets/images/dietpi-software-games-mineos.png
  docs/assets/images/dietpi-software-games-nukkit.png
  docs/assets/images/dietpi-software-games-opentyrian.jpg
  docs/assets/images/dietpi-software-games-steam.jpg
  docs/dietpi_docs_todo.md
  docs/dietpi_optimised_software.md
  docs/dietpi_tools.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/computational_science.md
  docs/software/desktop.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/load_balancer.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/ssh.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
  docs/software/wifi_hotspot.md
  mkdocs.yml
Labels: documentation

#178 dietpi-software command line install option described
  docs/assets/images/dietpi-tools-command-line-installation.png
  docs/dietpi_docs_todo.md
  docs/dietpi_tools.md
  docs/software/gaming.md
Labels: documentation

#180 Porting of social.md
  .wordlist.txt
  docs/assets/images/dietpi-software-social-baikal.png
  docs/assets/images/dietpi-software-social-freshrss.jpg
  docs/assets/images/dietpi-software-social-imagegallery.png
  docs/assets/images/dietpi-software-social-openbazaar.png
  docs/assets/images/dietpi-software-social-phpbb.png
  docs/assets/images/dietpi-software-social-wordpress.jpg
  docs/assets/images/dietpi-software-social-yacy.png
  docs/dietpi_optimised_software.md
  docs/software/social.md
Labels: documentation

#181 Porting home_automation.md
  .wordlist.txt
  docs/assets/images/dietpi-software-homeautomation-emonpi-emonPi-g2.jpg
  docs/assets/images/dietpi-software-homeautomation-emonpi-emonPi-g3.jpg
  docs/assets/images/dietpi-software-homeautomation-emonpi-emonPi-g4.jpg
  docs/assets/images/dietpi-software-homeautomation-emonpi-emonPi-g5.jpg
  docs/assets/images/dietpi-software-homeautomation-emonpi-emonPi-g6.jpg
  docs/assets/images/dietpi-software-homeautomation-emonpi-emonPi-g7.jpg
  docs/assets/images/dietpi-software-homeautomation-emonpi-emoncms-emonpi_addfeed.png
  docs/assets/images/dietpi-software-homeautomation-emonpi-emoncms-emonpi_inputs.png
  docs/assets/images/dietpi-software-homeautomation-emonpi.png
  docs/assets/images/dietpi-software-homeautomation-grasshopper.jpg
  docs/assets/images/dietpi-software-homeautomation-homeassistant.png
  docs/dietpi_optimised_software.md
  docs/software/home_automation.md
Labels: documentation
