Repository MichaIng/DietPi-Docs, pull requests merged in 2020-11, with the labels that each got.

#182 Porting cloud.md started
  .wordlist.txt
  docs/assets/images/dietpi-software-cloud-firefoxsyncserver.png
  docs/assets/images/dietpi-software-cloud-gitea.jpg
  docs/assets/images/dietpi-software-cloud-gogs.png
  docs/assets/images/dietpi-software-cloud-nextcloudtalk.png
  docs/assets/images/dietpi-software-cloud-owncloud.png
  docs/assets/images/dietpi-software-cloud-pydio.png
  docs/assets/images/dietpi-software-cloud-syncthing.png
  docs/assets/images/dietpi-software-cloud-tonido.png
  docs/assets/images/dietpi-software-cloud-urbackup.png
  docs/dietpi_optimised_software.md
  docs/software/cloud.md
Labels: documentation

#185 Enhancements cloud.md
  docs/dietpi_optimised_software.md
  docs/software/cloud.md
Labels: documentation

#186 Porting hardware_projects.md
  .wordlist.txt
  docs/assets/images/dietpi-software-hardwareprojects-audiophonics-gpionumbers.png
  docs/assets/images/dietpi-software-hardwareprojects-audiophonis-pcb.jpg
  docs/assets/images/dietpi-software-hardwareprojects-blynk.jpg
  docs/assets/images/dietpi-software-hardwareprojects-googleaiy-htop.png
  docs/assets/images/dietpi-software-hardwareprojects-googleaiy.jpg
  docs/assets/images/dietpi-software-hardwareprojects-gpio.png
  docs/assets/images/dietpi-software-hardwareprojects-grafana.png
  docs/assets/images/dietpi-software-hardwareprojects-influxdb.jpg
  docs/assets/images/dietpi-software-hardwareprojects-mosquitto.png
  docs/assets/images/dietpi-software-hardwareprojects-mycroftai.png
  docs/assets/images/dietpi-software-hardwareprojects-nodered.png
  docs/assets/images/dietpi-software-hardwareprojects-pijuice.jpg
  docs/assets/images/dietpi-software-hardwareprojects-webiopi.png
  docs/assets/images/dietpi-software-hardwareprojects-wiringpi.png
  docs/dietpi_optimised_software.md
  docs/software/hardware_projects.md
Labels: documentation

#193 Enhance and fix Remote Desktop, especially TigerVNC docs
  docs/software/remote_desktop.md
Labels: bug, documentation

#196 Changed '/' to '&' in the headings of the optimized software list
  docs/dietpi_docs_todo.md
  docs/dietpi_optimised_software.md
Labels: documentation

#198 Screenshot update
  docs/assets/images/dietpi-VirtualBox-import2.png
Labels: documentation

#199 Update gaming.md
  docs/software/gaming.md
Labels: bug

#200 Add PaperMC
  docs/assets/images/dietpi-software-games-papermc.jpg
  docs/dietpi_optimised_software.md
  docs/software/gaming.md
Labels: documentation

#202 Description of DietPi PREP script usage
  .wordlist.txt
  docs/assets/images/dietpi-prep-deviceselection.png
  docs/assets/images/dietpi-prep-finish.png
  docs/assets/images/dietpi-prep-preimage.png
  docs/assets/images/dietpi-prep-selectbranch.png
  docs/assets/images/dietpi-prep-wifiselection.png
  docs/assets/images/dietpi-software-webstack-selection.png
  docs/dietpi_sbc.md
  docs/software/webserver_stack.md
Labels: documentation

#203 Extend PaperMC description with Fuzon web page content
  .wordlist.txt
  docs/dietpi_docs_todo.md
  docs/software/gaming.md
Labels: documentation

#211 Deleted finished issues
  docs/dietpi_docs_todo.md
Labels: documentation

#214 Certbot description added and gitea description improvement
  docs/assets/images/dietpi-software-security-certbot.png
  docs/dietpi_docs_todo.md
  docs/dietpi_optimised_software.md
  docs/software/cloud.md
  docs/software/system_security.md
  docs/software/webserver_stack.md
Labels: enhancement

#216 Text beautification
  docs/software/cloud.md
Labels: documentation, enhancement

#219 Fix/enhance Mycroft AI Mimic section
  docs/software/hardware_projects.md
Labels: correction, enhancement

#217 Nextcloud hardening description (brute-force & Fail2Ban), text beautification
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/hardware_projects.md
  docs/software/media.md
  docs/software/social.md
Labels: new content

#221 Remove obsolete jRiver, Grasshopper and Raspcontrol
  .wordlist.txt
  docs/assets/images/dietpi-software-homeautomation-grasshopper.jpg
  docs/assets/images/dietpi-software-media-jriver.png
  docs/assets/images/dietpi-software-systemstat-raspcontrol.png
  docs/dietpi_optimised_software.md
  docs/software/home_automation.md
  docs/software/media.md
  docs/software/system_stats.md
Labels: correction

#218 Global commands (G_...) described
  docs/dietpi_docs_todo.md
  docs/dietpi_tools.md
Labels: enhancement

#225 Added TasmoAdmin and Domoticz to home_automation
  docs/assets/images/dietpi-software-homeautomation-domoticz.jpg
  docs/assets/images/dietpi-software-homeautomation-tasmoadmin.png
  docs/dietpi_optimised_software.md
  docs/software/home_automation.md
Labels: new content

#223 Added unbound description
  docs/assets/images/dietpi-software-dnsserver-unbound.svg
  docs/dietpi_optimised_software.md
  docs/software/dns_servers.md
Labels: extension

#224 DietPi Tools beautification
  docs/assets/images/dietpi-tools-cpuinfo.png
  docs/dietpi_docs_todo.md
  docs/dietpi_tools.md
Labels: enhancement

#201 [DRAFT] Update web development tools
  .wordlist.txt
  docs/assets/extra/software.json
  docs/assets/extra/software_categ.json
  docs/software/remote_desktop.md
  docs/software/webserver_stack.md
  mkdocs.yml
Labels: extension

#227 Description added for BruteFIR, Raspotify and Spotify web client
  .wordlist.txt
  docs/assets/images/dietpi-software-media-brutefir.gif
  docs/assets/images/dietpi-software-media-raspotify.png
  docs/dietpi_docs_todo.md
  docs/dietpi_optimised_software.md
  docs/software/media.md
Labels: new content

#254 Diet-Software | Gogs
  docs/software/cloud.md
Labels: correction

#251 New file "Development & Programming" added (see also issue #250)
  docs/assets/images/dietpi-software-programming-docker1.svg
  docs/assets/images/dietpi-software-programming-docker2.svg
  docs/assets/images/dietpi-software-programming-pythonlogo.png
  docs/dietpi_optimised_software.md
  docs/software/programming.md
  docs/software/system_security.md
  docs/software/webserver_stack.md
  mkdocs.yml
Labels: new content
