Repository MichaIng/DietPi-Docs, pull requests merged in 2020-12, with the labels that each got.

#253 Add Bitwarden_RS software documentation
  .wordlist.txt
  docs/assets/images/dietpi-software-cloud-bitwarden_rs.png
  docs/assets/images/import_cert_windows_1.png
  docs/assets/images/import_cert_windows_2.png
  docs/assets/images/import_cert_windows_3.png
  docs/assets/images/import_cert_windows_4.png
  docs/assets/images/import_cert_windows_5.png
  docs/assets/images/import_cert_windows_6.png
  docs/dietpi_optimised_software.md
  docs/software/cloud.md
  mkdocs.yml
Labels: new content

#257 Shorten software headers > URLs
  .wordlist.txt
  docs/dietpi_optimised_software.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/desktop.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/load_balancer.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/ssh.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/wifi_hotspot.md
Labels: enhancement

#262 ToDo file removed, Python desc. enhanced
  docs/dietpi_docs_todo.md
  docs/software/programming.md
  mkdocs.yml
Labels: enhancement

#261 Release week 49
  .github/workflows/actions.yml
  .markdownlint.yml
  .spellcheck.yml
  .wordlist.txt
  docs/assets/images/dietpi-software-cloud-bitwarden_rs.png
  docs/assets/images/dietpi-software-dnsserver-unbound.svg
  docs/assets/images/dietpi-software-homeautomation-domoticz.jpg
  docs/assets/images/dietpi-software-homeautomation-grasshopper.jpg
  docs/assets/images/dietpi-software-homeautomation-tasmoadmin.png
  docs/assets/images/dietpi-software-media-brutefir.gif
  docs/assets/images/dietpi-software-media-jriver.png
  docs/assets/images/dietpi-software-media-raspotify.png
  docs/assets/images/dietpi-software-programming-docker1.svg
  docs/assets/images/dietpi-software-programming-docker2.svg
  docs/assets/images/dietpi-software-programming-pythonlogo.png
  docs/assets/images/dietpi-software-security-certbot.png
  docs/assets/images/dietpi-software-systemstat-raspcontrol.png
  docs/assets/images/dietpi-software-webstack-apache2.jpg
  docs/assets/images/dietpi-software-webstack-influxdb.svg
  docs/assets/images/dietpi-software-webstack-lighttpd.svg
  docs/assets/images/dietpi-software-webstack-mariadb.png
  docs/assets/images/dietpi-software-webstack-nginx.gif
  docs/assets/images/dietpi-software-webstack-php.svg
  docs/assets/images/dietpi-software-webstack-phpmyadmin.png
  docs/assets/images/dietpi-software-webstack-redis.svg
  docs/assets/images/dietpi-software-webstack-sqlite.svg
  docs/assets/images/dietpi-software-webstack-tomcat.svg
  docs/assets/images/dietpi-tools-cpuinfo.png
  docs/assets/images/import_cert_windows_1.png
  docs/assets/images/import_cert_windows_2.png
  docs/assets/images/import_cert_windows_3.png
  docs/assets/images/import_cert_windows_4.png
  docs/assets/images/import_cert_windows_5.png
  docs/assets/images/import_cert_windows_6.png
  docs/dietpi_docs_todo.md
  docs/dietpi_optimised_software.md
  docs/dietpi_tools.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/desktop.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/load_balancer.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/ssh.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
  docs/software/wifi_hotspot.md
  mkdocs.yml
Labels: release

#266 Move WiFi hotspots to Advanced Networking
  docs/assets/images/dietpi-software-advanced-networking-noip.jpg
  docs/assets/images/dietpi-software-advanced-networking-torhotspot.png
  docs/assets/images/dietpi-software-advanced-networking-wifihotspot.png
  docs/software/advanced_networking.md
  docs/software/dns_servers.md
  docs/software/wifi_hotspot.md
  mkdocs.yml
Labels: meta

#267 DietPi-Software | Grafana: update password
  docs/software/hardware_projects.md
Labels: correction

#268 Fix documented default password on all download tools
  docs/software/bittorrent.md
Labels: correction

#269 Remove CloudPrint and align list
  docs/dietpi_optimised_software.md
  docs/software/printing.md
  mkdocs.yml
Labels: correction

#276 Rename "Image Gallery" to "Single File PHP Gallery"
  docs/dietpi_optimised_software.md
  docs/software/social.md
Labels: correction

#277 Extend the Tor Relay nyx monitoring docs a bit
  docs/software/advanced_networking.md
Labels: extension

#273 Add Pi A400 to the supported SBCs
  docs/dietpi_sbc.md
Labels: enhancement

#278 Show Tor Relay image smaller
  docs/software/advanced_networking.md
Labels: correction

#279 Documentation for media package Jellyfin added
  docs/assets/images/dietpi-software-media-jellyfin.jpg
  docs/dietpi_optimised_software.md
  docs/software/media.md
Labels: new content

#280 Enhance/fix IceCast docs
  docs/software/media.md
Labels: correction, enhancement

#275 Release week 50
  .wordlist.txt
  docs/assets/images/dietpi-software-advanced-networking-haproxy.jpg
  docs/assets/images/dietpi-software-advanced-networking-haproxy2.jpg
  docs/assets/images/dietpi-software-advanced-networking-high-availability.gif
  docs/assets/images/dietpi-software-advanced-networking-layer4.jpg
  docs/assets/images/dietpi-software-advanced-networking-noip.jpg
  docs/assets/images/dietpi-software-advanced-networking-tor.png
  docs/assets/images/dietpi-software-advanced-networking-torhotspot.png
  docs/assets/images/dietpi-software-advanced-networking-wifihotspot.png
  docs/assets/images/dietpi-software-media-jellyfin.jpg
  docs/dietpi_optimised_software.md
  docs/dietpi_sbc.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/dns_servers.md
  docs/software/load_balancer.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/social.md
  docs/software/wifi_hotspot.md
  mkdocs.yml
Labels: release

#286 Beautification of screenshots
  docs/assets/images/dietpi-software-cloud-bitwarden_rs.png
  docs/software/cloud.md
  docs/software/dns_servers.md
  docs/software/gaming.md
Labels: enhancement

#285 wordlist cleanup
  .github/workflows/actions.yml
  .wordlist.txt
  docs/dietpi_optimised_software.md
  docs/dietpi_sbc.md
  docs/dietpi_tools.md
  docs/index.md
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/computational_science.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/webserver_stack.md
  docs/user-guide_installation.md
  docs/user-guide_overview.md
Labels: correction

#292 Update OctoPrint docs for DietPi v6.34
  .github/workflows/actions.yml
  .wordlist.txt
  docs/assets/images/dietpi-software-printserver-cups.png
  docs/release-notes.md
  docs/software/printing.md
Labels: correction

#295 wordlist fixes
  .wordlist.txt
  docs/software/webserver_stack.md
Labels: correction

#289 Release week 51
  .github/workflows/actions.yml
  .wordlist.txt
  docs/assets/images/dietpi-automated_APT_package_update.jpg
  docs/assets/images/dietpi-docs-categories.jpg
  docs/assets/images/dietpi-raspberry-pi-400-back.jpg
  docs/assets/images/dietpi-release-gift.jpg
  docs/assets/images/dietpi-software-advanced-networking-tor.png
  docs/assets/images/dietpi-software-bitwarden_rs.jpg
  docs/assets/images/dietpi-software-cloud-bitwarden_rs.png
  docs/assets/images/dietpi-software-papermc.jpg
  docs/assets/images/dietpi-software-portainer.jpg
  docs/assets/images/dietpi-software-printserver-cups.png
  docs/assets/images/dietpi-software-unbound.jpg
  docs/dietpi_optimised_software.md
  docs/dietpi_sbc.md
  docs/dietpi_tools.md
  docs/index.md
  docs/release-notes.md
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/computational_science.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/webserver_stack.md
  docs/user-guide_installation.md
  docs/user-guide_overview.md
  mkdocs.yml
Labels: release

#300 DietPi-Software | SAMBA
  docs/software/file_servers.md
Labels: correction

#302 DietPi-Software | XRDP
  docs/software/remote_desktop.md
Labels: correction

#301 DietPi-Software | Portainer
  docs/software/programming.md
Labels: extension

#306 Beautification: Horizontal line behind tab areas
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/desktop.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/ssh.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
Labels: enhancement
