Repository MichaIng/DietPi-Docs, pull requests merged in 2021-03, with the labels that each got.

#389 Virtual machine hint: IPv6 deactivation
  .wordlist.txt
  docs/assets/images/dietpi-VirtualBox-IPv6.png
  docs/install.md
  docs/software/dns_servers.md
Labels: enhancement

#390 Minor fixes and add mjpg-streamer logging docs
  docs/software/camera.md
  docs/software/dns_servers.md
Labels: correction, extension

#391 Add a nice general DietPi video in references
  docs/references.md
Labels: enhancement

#394 Harmonization of WiFi configuration description
  docs/install.md
Labels: enhancement

#393 Description of the mount option extended / corrected
  docs/software/file_servers.md
Labels: correction, extension

#392 Release week 10
  .wordlist.txt
  README.md
  docs/assets/images/dietpi-VirtualBox-IPv6.png
  docs/install.md
  docs/references.md
  docs/releases.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
Labels: release

#398 Remove Firefly RK3399 from supported devices
  docs/hardware.md
Labels: correction

#399 Installation video "MotionEye" link added
  docs/software/camera.md
Labels: extension

#397 Page load performance enhancements - part 3
  .wordlist.txt
  docs/assets/images/dietpi-software-hardwareprojects-influxdb.jpg
  docs/software/cloud.md
  docs/software/desktop.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/media.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
Labels: performance

#403 Reference port numbers outside code blocks
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/computational_science.md
  docs/software/dns_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/social.md
  docs/software/system_stats.md
  docs/software/webserver_stack.md
Labels: correction

#401 Release week 11
  .wordlist.txt
  docs/assets/images/dietpi-software-hardwareprojects-influxdb.jpg
  docs/hardware.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/computational_science.md
  docs/software/desktop.md
  docs/software/dns_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
Labels: release

#405 Clearification of hostname at first boot
  docs/install.md
Labels: enhancement

#407 Minor SBC install clarifications
  docs/install.md
Labels: enhancement

#408 Extend Unbound (DoT) description
  docs/software/dns_servers.md
Labels: extension

#409 Release week 13
  docs/install.md
  docs/software/dns_servers.md
Labels: release
