Repository MichaIng/DietPi-Docs, pull requests merged in 2021-01, with the labels that each got.

#307 Release week 53
  .wordlist.txt
  docs/assets/images/dietpi-software-cloud-minio.jpg
  docs/dietpi_optimised_software.md
  docs/release-notes.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/desktop.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/ssh.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
Labels: release

#308 Links to videos, articles, sites added
  .wordlist.txt
  docs/dietpi_references.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/media.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
  docs/user-guide_installation.md
  mkdocs.yml
Labels: enhancement

#309 Video embedding instead of linking
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/media.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
Labels: enhancement

#310 Fix and align PaperMC docs
  .github/workflows/actions.yml
  docs/software/gaming.md
Labels: correction, enhancement

#312 Release week 02
  .github/workflows/actions.yml
  .spellcheck.yml
  .wordlist.txt
  docs/dietpi_references.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/media.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
  docs/user-guide_installation.md
  mkdocs.yml
Labels: release

#313 Moved FAQ to a tab
  docs/software/gaming.md
Labels: enhancement

#314 Gaming page enhancements and fixes
  .github/workflows/actions.yml
  .spellcheck.yml
  docs/software/gaming.md
  mkdocs.yml
Labels: correction, enhancement

#315 Beautification: Key images
  docs/dietpi_sbc.md
  docs/dietpi_tools.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/media.md
  docs/user-guide_installation.md
Labels: enhancement

#316 Release week 3
  .github/workflows/actions.yml
  .spellcheck.yml
  docs/dietpi_sbc.md
  docs/dietpi_tools.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/media.md
  docs/user-guide_installation.md
  mkdocs.yml
Labels: release

#318 DietPi-Software | Logitech Media Server
  docs/software/media.md
Labels: extension

#319 Shorten URLs and add redirects
  .spellcheck.yml
  docs/dietpi_tools.md
  docs/getting_started.md
  docs/hardware.md
  docs/index.md
  docs/install.md
  docs/references.md
  docs/releases.md
  docs/software.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/computational_science.md
  docs/software/desktop.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/ssh.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
  mkdocs.yml
Labels: enhancement

#320 Release week 4
  .spellcheck.yml
  docs/dietpi_tools.md
  docs/getting_started.md
  docs/hardware.md
  docs/index.md
  docs/install.md
  docs/references.md
  docs/releases.md
  docs/software.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/computational_science.md
  docs/software/desktop.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/ssh.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
  mkdocs.yml
Labels: release

#323 Plex: Link to tutorial added
  docs/software/camera.md
  docs/software/media.md
Labels: enhancement

#324 References and Pi-hole extensions
  .wordlist.txt
  docs/references.md
  docs/software/dns_servers.md
  mkdocs.yml
Labels: enhancement

#322 Add instructions to add a trusted certificate for macOS
  docs/assets/images/import_cert_mac_1.png
  docs/assets/images/import_cert_mac_2.png
  docs/assets/images/import_cert_mac_3.png
  docs/assets/images/import_cert_mac_4.png
  docs/assets/images/import_cert_mac_5.png
  docs/dietpi_tools.md
  docs/hardware.md
  docs/releases.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/computational_science.md
  docs/software/dns_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/ssh.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
Labels: extension
