Repository MichaIng/DietPi-Docs, pull requests merged in 2021-04, with the labels that each got.

#411 Add Gitea update info
  .github/workflows/actions.yml
  .wordlist.txt
  docs/software/cloud.md
  docs/software/dns_servers.md
  docs/software/hardware_projects.md
Labels: enhancement

#414 VirtualBox time synchronisation description added
  docs/assets/images/dietpi-config-timesync.png
  docs/dietpi_tools.md
  docs/install.md
Labels: extension

#417 Extend and align IceCast docs
  docs/software/media.md
Labels: extension

#415 Release week 14
  .github/workflows/actions.yml
  .wordlist.txt
  docs/assets/images/dietpi-VirtualBox-IPv6.png
  docs/assets/images/dietpi-config-timesync.png
  docs/assets/images/dietpi-docker-compose.png
  docs/dietpi_tools.md
  docs/hardware.md
  docs/install.md
  docs/software/cloud.md
  docs/software/dns_servers.md
  docs/software/hardware_projects.md
  docs/software/media.md
Labels: release

#419 Referencing of Pi-Hole/Unbound blog in documentation
  docs/software/dns_servers.md
Labels: extension

#421 Update description updated
  docs/software/cloud.md
Labels: correction

#427 HowTo: Logging description
  .wordlist.txt
  docs/assets/images/dietpi-howto-logging1.png
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/computational_science.md
  docs/software/hardware_projects.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/programming.md
  docs/software/vpn.md
  docs/usage.md
  mkdocs.yml
Labels: new content

#432 Pi-Hole/Unbound Blog entry added
  docs/software/dns_servers.md
Labels: extension

#430 Clarify Netdata > Troubleshooting
  docs/software/system_stats.md
Labels: enhancement

#441 Changed heading from "Python" to "Python 3"
  docs/releases.md
  docs/software.md
  docs/software/bittorrent.md
  docs/software/media.md
  docs/software/programming.md
  docs/software/webserver_stack.md
Labels: correction

#438 Release week 16
  .github/workflows/actions.yml
  .wordlist.txt
  docs/assets/images/dietpi-howto-logging1.png
  docs/releases.md
  docs/software.md
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/computational_science.md
  docs/software/dns_servers.md
  docs/software/hardware_projects.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/programming.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
  docs/usage.md
  mkdocs.yml
Labels: release

#445 DietPi-Software | CUPS
  docs/assets/images/dietpi-software-printserver-cups.png
  docs/software.md
  docs/software/printing.md
Labels: Next DietPi release, new content

#406 Add DietPi-VPN
  .wordlist.txt
  docs/assets/images/dietpi-nordvpn.jpg
  docs/assets/images/dietpi-software-vpn-nordvpn-logo.png
  docs/assets/images/dietpi-software-vpn-nordvpn.jpg
  docs/assets/images/dietpi-vpn.jpg
  docs/assets/images/nordvpn-logo.svg
  docs/dietpi_tools.md
  docs/releases.md
  docs/software.md
  docs/software/bittorrent.md
  docs/software/vpn.md
Labels: Next DietPi release, extension

#413 Extend Mosquitto docs
  .wordlist.txt
  docs/software/hardware_projects.md
Labels: Next DietPi release, correction, extension

#418 Update IceCast web interface admin password
  docs/software/media.md
Labels: Next DietPi release, correction, enhancement

#424 Update software listening port
  .wordlist.txt
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/hardware_projects.md
  docs/software/media.md
  docs/software/printing.md
Labels: Next DietPi release, correction

#426 Add IPFS Node docs and new distributed projects category
  .wordlist.txt
  docs/assets/images/dietpi-software-distributed-projects-foldingathome.png
  docs/assets/images/dietpi-software-distributed-projects-ipfs.png
  docs/assets/images/dietpi-software-distributed-projects-yacy.png
  docs/assets/images/dietpi-software-tor-logo.png
  docs/releases.md
  docs/software.md
  docs/software/advanced_networking.md
  docs/software/computational_science.md
  docs/software/distributed_projects.md
  docs/software/social.md
  mkdocs.yml
Labels: Next DietPi release, extension

#440 No-IP removed from software packages
  docs/software.md
  docs/software/advanced_networking.md
Labels: Next DietPi release, correction

#444 Add VSCodium Docs
  .wordlist.txt
  docs/assets/images/dietpi-software-programming-vscodium.png
  docs/software.md
  docs/software/programming.md
Labels: Next DietPi release, extension

#457 Spell check issues
  docs/software/distributed_projects.md
  docs/software/printing.md
Labels: correction

#459 Release notes 7.1 (updates)
  docs/assets/images/dietpi-release-ipfs.jpg
  docs/assets/images/dietpi-software-printing-cups.png
  docs/assets/images/dietpi-software-programming-go.jpg
  docs/assets/images/dietpi-tools-letsencrypt-tlscheck.jpg
  docs/assets/images/dietpi-version7.1.jpg
  docs/releases.md
Labels: Next DietPi release, new content

#460 Add description of the Go language
  .wordlist.txt
  docs/assets/images/dietpi-software-programming-golang.svg
  docs/software/programming.md
Labels: Next DietPi release, enhancement, new content

#463 Minor changes
  docs/software.md
  docs/software/databases.md
  docs/software/programming.md
Labels: correction

#464 Editorial changes
  docs/dietpi_tools.md
  docs/getting_started.md
  docs/software.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/databases.md
  docs/software/desktop.md
  docs/software/distributed_projects.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/ssh.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
Labels: correction

#468 [Node-RED] Skip audit output on update
  docs/software/hardware_projects.md
Labels: enhancement

#465 Release information beautification
  docs/assets/images/dietpi-releaseinformation-7.2.svg
  docs/releases.md
Labels: enhancement

#469 Add DietPi-DDNS docs
  .wordlist.txt
  docs/assets/images/dietpi-ddns.jpg
  docs/dietpi_tools.md
  docs/software/remote_desktop.md
Labels: Next DietPi release, extension

#470 Release week 17
  .wordlist.txt
  docs/assets/images/dietpi-ddns.jpg
  docs/assets/images/dietpi-nordvpn.jpg
  docs/assets/images/dietpi-release-ddns-selection.jpg
  docs/assets/images/dietpi-release-ddns.jpg
  docs/assets/images/dietpi-release-ipfs.jpg
  docs/assets/images/dietpi-release-single-software-list.jpg
  docs/assets/images/dietpi-release-vpn-selection.jpg
  docs/assets/images/dietpi-release-vpn.jpg
  docs/assets/images/dietpi-releaseinformation-7.2.svg
  docs/assets/images/dietpi-software-additional.jpg
  docs/assets/images/dietpi-software-distributed-projects-foldingathome.png
  docs/assets/images/dietpi-software-distributed-projects-ipfs.png
  docs/assets/images/dietpi-software-distributed-projects-yacy.png
  docs/assets/images/dietpi-software-printing-cups.png
  docs/assets/images/dietpi-software-printserver-cups.png
  docs/assets/images/dietpi-software-programming-go.jpg
  docs/assets/images/dietpi-software-programming-golang.svg
  docs/assets/images/dietpi-software-programming-vscodium.png
  docs/assets/images/dietpi-software-tor-logo.png
  docs/assets/images/dietpi-software-vpn-nordvpn-logo.png
  docs/assets/images/dietpi-software-vpn-nordvpn.jpg
  docs/assets/images/dietpi-software.jpg
  docs/assets/images/dietpi-tools-letsencrypt-tlscheck.jpg
  docs/assets/images/dietpi-version-71.jpg
  docs/assets/images/dietpi-vpn.jpg
  docs/assets/images/nordvpn-logo.svg
  docs/dietpi_tools.md
  docs/getting_started.md
  docs/releases.md
  docs/software.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/computational_science.md
  docs/software/databases.md
  docs/software/desktop.md
  docs/software/distributed_projects.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/ssh.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
  mkdocs.yml
Labels: release
