Repository MichaIng/DietPi-Docs, pull requests merged in 2021-08, with the labels that each got.

#546 Fix and enhance Blynk server docs
  docs/software/hardware_projects.md
Labels: correction, enhancement

#550 Release notes DietPi 7.5
  docs/assets/images/dietpi-version-75-debian11.jpg
  docs/releases.md
Labels: extension

#551 Colour change
  docs/assets/images/second-nav-blue.png
  docs/css/custom.css
Labels: enhancement

#553 Release week 33
  docs/assets/images/dietpi-version-75-debian11.jpg
  docs/assets/images/second-nav-blue.png
  docs/css/custom.css
  docs/releases.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/media.md
Labels: release

#554 Complement v7.5 changelog
  .github/workflows/actions.yml
  docs/releases.md
  docs/software/remote_desktop.md
Labels: correction, release

#556 Add brief Stretch => Buster upgrade instructions
  .wordlist.txt
  docs/releases.md
  docs/usage.md
Labels: new content

#557 Release week 34
  .wordlist.txt
  docs/releases.md
  docs/usage.md
Labels: release
