Repository MichaIng/DietPi-Docs, pull requests merged in 2021-05, with the labels that each got.

#477 Update TigerVNC download URL
  docs/software/remote_desktop.md
Labels: correction

#475 Add official Webmin docs link and align official links text
  docs/software/system_stats.md
Labels: extension

#481 Add some info about Go language
  .wordlist.txt
  docs/software/programming.md
Labels: extension

#484 Release week 20
  .wordlist.txt
  docs/software/cloud.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/system_stats.md
Labels: release

#489 Release notes DietPi 7.2 (initial)
  docs/releases.md
Labels: extension

#491 Beta v7.2 release
  docs/releases.md
Labels: release

#493 Release notes 7.2 (updates)
  docs/releases.md
Labels: enhancement

#486 Update InfluxDB docs and remove logo
  docs/software/databases.md
Labels: correction

#478 DietPi-Software | vaultwarden: Rename from Bitwarden_RS
  .wordlist.txt
  docs/assets/images/dietpi-software-vaultwarden.jpg
  docs/releases.md
  docs/software.md
  docs/software/cloud.md
Labels: Next DietPi release, correction

#483 Update emonPi/emonHub docs
  .wordlist.txt
  docs/software.md
  docs/software/home_automation.md
Labels: Next DietPi release, correction

#495 Expand release notes 7.2
  docs/assets/images/dietpi-banner.jpg
  docs/assets/images/dietpi-banner_config.jpg
  docs/assets/images/dietpi-nanopi_r1.jpg
  docs/assets/images/dietpi-nanopi_r4s.jpg
  docs/assets/images/dietpi-pinebook-pro.jpg
  docs/dietpi_tools.md
  docs/releases.md
Labels: enhancement

#494 Release week 21 (DietPi v7.2 release)
  .wordlist.txt
  docs/assets/images/Fx-Browser-icon-fullColor-64.png
  docs/assets/images/dietpi-banner.jpg
  docs/assets/images/dietpi-banner_config.jpg
  docs/assets/images/dietpi-ddns.jpg
  docs/assets/images/dietpi-nanopi_r1.jpg
  docs/assets/images/dietpi-nanopi_r4s.jpg
  docs/assets/images/dietpi-pinebook-pro.jpg
  docs/assets/images/dietpi-releaseinformation-7.2.svg
  docs/assets/images/dietpi-software-browser-preference.jpg
  docs/assets/images/dietpi-software-firefox-display.png
  docs/assets/images/dietpi-software-firefox.png
  docs/assets/images/dietpi-software-nodejs.jpg
  docs/assets/images/dietpi-software-vaultwarden.jpg
  docs/dietpi_tools.md
  docs/releases.md
  docs/software.md
  docs/software/cloud.md
  docs/software/databases.md
  docs/software/desktop.md
  docs/software/home_automation.md
  docs/software/programming.md
  docs/software/webserver_stack.md
Labels: release

#498 Pi-hole default log TTL reduced to 2 days
  .wordlist.txt
  docs/releases.md
  docs/software/dns_servers.md
Labels: Next DietPi release

#500 Complement for DietPi v7.2 release
  .wordlist.txt
  docs/releases.md
  docs/software/dns_servers.md
Labels: release
