Repository MichaIng/DietPi-Docs, pull requests merged in 2021-02, with the labels that each got.

#327 Moved "Report issues" and "Request features" from HOME to COMMUNITY
  mkdocs.yml
Labels: enhancement

#325 Release week 5
  .wordlist.txt
  docs/assets/images/import_cert_mac_1.png
  docs/assets/images/import_cert_mac_2.png
  docs/assets/images/import_cert_mac_3.png
  docs/assets/images/import_cert_mac_4.png
  docs/assets/images/import_cert_mac_5.png
  docs/dietpi_tools.md
  docs/hardware.md
  docs/references.md
  docs/releases.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/computational_science.md
  docs/software/dns_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/ssh.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
  mkdocs.yml
Labels: release

#328 Add Box86 and Steam on ARM
  .wordlist.txt
  docs/software.md
  docs/software/gaming.md
Labels: extension

#329 Rename Xfce Power Manager
  docs/software.md
  docs/software/desktop.md
Labels: correction

#331 Description of dietpi-drive_manager extended
  .wordlist.txt
  docs/assets/images/dietpi-drive-manager_2.png
  docs/assets/images/dietpi-drive-manager_3.png
  docs/assets/images/dietpi-drive-manager_4.png
  docs/assets/images/dietpi-drive-manager_5.png
  docs/assets/images/dietpi-drive-manager_6.png
  docs/assets/images/dietpi-drive-manager_7.png
  docs/assets/images/dietpi-drive-manager_8.png
  docs/dietpi_tools.md
Labels: extension

#330 DietPi-Software | Docker Compose
  docs/software.md
  docs/software/programming.md
Labels: new content

#333 Enhanced description of dietpi-survey
  docs/dietpi_tools.md
Labels: extension

#334 Logo for advanxer.com added
  .wordlist.txt
  docs/assets/images/dietpi-references-advanxer.com-logo.png
  docs/references.md
Labels: enhancement

#335 WireGuard VPN: Added english youtube tutorial
  docs/software/vpn.md
Labels: enhancement

#341 Release week 6
  .wordlist.txt
  README.md
  docs/assets/images/dietpi-drive-manager_2.png
  docs/assets/images/dietpi-drive-manager_3.png
  docs/assets/images/dietpi-drive-manager_4.png
  docs/assets/images/dietpi-drive-manager_5.png
  docs/assets/images/dietpi-drive-manager_6.png
  docs/assets/images/dietpi-drive-manager_7.png
  docs/assets/images/dietpi-drive-manager_8.png
  docs/assets/images/dietpi-references-advanxer.com-logo.png
  docs/dietpi_tools.md
  docs/references.md
  docs/socialmedia.md
  docs/software.md
  docs/software/desktop.md
  docs/software/gaming.md
  docs/software/programming.md
  docs/software/vpn.md
  mkdocs.yml
Labels: release

#347 Missing command at Mopidy description
  docs/software/media.md
Labels: correction

#346 DietPi on VMware installation description added
  docs/assets/images/dietpi-VMware-7zip-file.png
  docs/assets/images/dietpi-VMware-Download.png
  docs/assets/images/dietpi-VMware-VM-Machine.png
  docs/assets/images/dietpi-VMware-import1.png
  docs/assets/images/dietpi-VMware-program.png
  docs/install.md
Labels: new content

#349 DietPi-Software | Tonido
  docs/software.md
  docs/software/cloud.md
Labels: correction

#352 Menu restructure of dietpi_tools.md
  docs/assets/images/dietpi-backup_1.png
  docs/assets/images/dietpi-justboom.jpg
  docs/assets/images/dietpi-justboom_2.jpg
  docs/dietpi_tools.md
Labels: enhancement, extension

#351 Release week 7
  README.md
  docs/assets/images/dietpi-VMware-7zip-file.png
  docs/assets/images/dietpi-VMware-Download.png
  docs/assets/images/dietpi-VMware-VM-Machine.png
  docs/assets/images/dietpi-VMware-import1.png
  docs/assets/images/dietpi-VMware-program.png
  docs/assets/images/dietpi-backup_1.png
  docs/assets/images/dietpi-justboom.jpg
  docs/assets/images/dietpi-justboom_2.jpg
  docs/assets/images/dietpi-references-advanxer.com-logo.png
  docs/assets/images/dietpi-software-cloud-tonido.png
  docs/dietpi_tools.md
  docs/install.md
  docs/software.md
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/media.md
  overrides/main.html
Labels: release

#357 Description of DietPi tools site extended
  docs/assets/images/dietpi-letsencrypt_2.png
  docs/assets/images/dietpi-services_2.png
  docs/dietpi_tools.md
Labels: extension

#358 DietPi-Software | Unbound
  docs/software/dns_servers.md
Labels: correction, extension

#361 Fix and remove doubled CPU info command
  docs/dietpi_tools.md
Labels: correction

#362 Add an info about how to view logs for Emby server
  docs/software/media.md
Labels: extension

#363 Dietpi-Cleaner description extended
  docs/assets/images/dietpi-cleaner_2.png
  docs/assets/images/dietpi-cleaner_3.png
  docs/dietpi_tools.md
Labels: extension

#367 Add more info on how to monitor Tor relays
  .wordlist.txt
  docs/dietpi_tools.md
  docs/software/advanced_networking.md
Labels: enhancement

#366 Optimise image and YouTube loading
  .wordlist.txt
  README.md
  docs/dietpi_tools.md
  docs/getting_started.md
  docs/hardware.md
  docs/index.md
  docs/install.md
  docs/references.md
  docs/releases.md
  docs/software/dns_servers.md
Labels: correction, performance

#371 Description of PC installation extended
  .wordlist.txt
  docs/assets/images/dietpi-download-nativepc-bios.jpg
  docs/assets/images/dietpi-download-nativepc-uefi.jpg
  docs/assets/images/dietpi-rufus-bios-direct-write-image.png
  docs/assets/images/dietpi-rufus-bios-installer.png
  docs/assets/images/dietpi-rufus-uefi-installer.png
  docs/assets/images/dietpi-rufus-uefi.jpg
  docs/install.md
Labels: new content

#370 Release week 8
  .wordlist.txt
  README.md
  docs/assets/images/dietpi-cleaner_2.png
  docs/assets/images/dietpi-cleaner_3.png
  docs/assets/images/dietpi-download-nativepc-bios.jpg
  docs/assets/images/dietpi-download-nativepc-uefi.jpg
  docs/assets/images/dietpi-letsencrypt_2.png
  docs/assets/images/dietpi-rufus-bios-direct-write-image.png
  docs/assets/images/dietpi-rufus-bios-installer.png
  docs/assets/images/dietpi-rufus-uefi-installer.png
  docs/assets/images/dietpi-rufus-uefi.jpg
  docs/assets/images/dietpi-services_2.png
  docs/dietpi_tools.md
  docs/getting_started.md
  docs/hardware.md
  docs/index.md
  docs/install.md
  docs/references.md
  docs/releases.md
  docs/software/advanced_networking.md
  docs/software/dns_servers.md
  docs/software/hardware_projects.md
  docs/software/media.md
  mkdocs.yml
Labels: release

#376 Description for Hyper-V installation added, added ESXi link in VMware
  .wordlist.txt
  docs/assets/images/dietpi-HyperV-Download.jpg
  docs/assets/images/dietpi-HyperV-VM-generation.png
  docs/assets/images/dietpi-HyperV-activation.png
  docs/assets/images/dietpi-HyperV-boot-wo-network.jpg
  docs/assets/images/dietpi-HyperV-connect-machine.png
  docs/assets/images/dietpi-HyperV-manage-network.png
  docs/assets/images/dietpi-HyperV-program.png
  docs/assets/images/dietpi-HyperV-safe-start.png
  docs/assets/images/dietpi-HyperV-start-machine.png
  docs/install.md
Labels: new content

#379 Enhance page load performance - part 2
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/computational_science.md
  docs/software/log_system.md
  docs/software/printing.md
  docs/software/ssh.md
  docs/software/system_security.md
Labels: performance

#380 Add mjpg-streamer documentation
  .wordlist.txt
  docs/assets/images/mjpg-streamer.gif
  docs/software.md
  docs/software/camera.md
Labels: extension

#383 Remove Netdata Pi-hole monitor docs
  docs/software/dns_servers.md
  docs/software/system_stats.md
Labels: correction, performance

#381 Extend release notes v.7
  docs/assets/images/dietpi-docker-compose.png
  docs/assets/images/dietpi-version7.jpg
  docs/releases.md
  docs/software/programming.md
Labels: extension

#384 DietPi v7.0 co-release
  .github/workflows/actions.yml
  .wordlist.txt
  README.md
  docs/assets/images/dietpi-HyperV-Download.jpg
  docs/assets/images/dietpi-HyperV-VM-generation.png
  docs/assets/images/dietpi-HyperV-activation.png
  docs/assets/images/dietpi-HyperV-boot-wo-network.jpg
  docs/assets/images/dietpi-HyperV-connect-machine.png
  docs/assets/images/dietpi-HyperV-manage-network.png
  docs/assets/images/dietpi-HyperV-program.png
  docs/assets/images/dietpi-HyperV-safe-start.png
  docs/assets/images/dietpi-HyperV-start-machine.png
  docs/assets/images/dietpi-docker-compose.png
  docs/assets/images/dietpi-version7.jpg
  docs/assets/images/mjpg-streamer.gif
  docs/hardware.md
  docs/install.md
  docs/releases.md
  docs/software.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/computational_science.md
  docs/software/dns_servers.md
  docs/software/log_system.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/ssh.md
  docs/software/system_security.md
  docs/software/system_stats.md
Labels: release
