Repository MichaIng/DietPi-Docs, pull requests merged in 2021-06, with the labels that each got.

#505 Add newly supported SBCs
  docs/hardware.md
Labels: extension

#512 Release week 23
  docs/assets/images/Fx-Browser-icon-fullColor-64.png
  docs/assets/images/dietpi-firefly-rk3399.png
Labels: release

#291 Migrate to lychee for link checking
  .github/workflows/actions.yml
  docs/dietpi_tools.md
  docs/install.md
  docs/releases.md
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/distributed_projects.md
  docs/software/hardware_projects.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/remote_desktop.md
Labels: correction, meta

#518 Add beets docs
  docs/assets/images/dietpi-software-media-beets.png
  docs/software.md
  docs/software/media.md
Labels: Next DietPi release, new content

#515 Add AdGuard Home docs
  docs/assets/images/dietpi-software-dnsserver-adguardhome.png
  docs/software.md
  docs/software/dns_servers.md
Labels: Next DietPi release, new content

#517 Docs for K3s
  docs/assets/images/logo-k3s.svg
  docs/software.md
  docs/software/system_stats.md
Labels: Next DietPi release, new content

#510 Snapcast docs (client and server)
  docs/assets/images/dietpi-software-media-snapcast.png
  docs/software.md
  docs/software/media.md
Labels: Next DietPi release, new content

#521 Add frp docs
  .wordlist.txt
  docs/software.md
  docs/software/advanced_networking.md
Labels: Next DietPi release, new content

#525 Release week 25
  .github/workflows/actions.yml
  .wordlist.txt
  docs/assets/images/dietpi-software-cloud-fuguhub.png
  docs/assets/images/dietpi-software-dnsserver-adguard.gif
  docs/assets/images/dietpi-software-dnsserver-adguardhome.png
  docs/assets/images/dietpi-software-frp.png
  docs/assets/images/dietpi-software-media-beets.png
  docs/assets/images/dietpi-software-media-snapcast-client.jpg
  docs/assets/images/dietpi-software-media-snapcast.png
  docs/assets/images/logo-k3s.svg
  docs/dietpi_tools.md
  docs/install.md
  docs/releases.md
  docs/software.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/distributed_projects.md
  docs/software/dns_servers.md
  docs/software/hardware_projects.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/remote_desktop.md
  docs/software/system_stats.md
  docs/software/webserver_stack.md
Labels: release

#526 DietPi-Software | AdGuard Home
  docs/software/dns_servers.md
Labels: correction

#527 DietPi-Software | frp
  docs/software/advanced_networking.md
Labels: correction

#528 Linking to our DietPi Blog page added
  docs/references.md
  docs/socialmedia.md
  mkdocs.yml
Labels: enhancement
