Repository MichaIng/DietPi-Docs, pull requests merged in 2021-12, with the labels that each got.

#621 Add instructions for password management with DietPi-Dashboard
  docs/software/system_stats.md
Labels: extension, Next DietPi release

#589 Implement single line tabs style required for mkdocs-material now
  docs/assets/stylesheets/custom.css
  overrides/main.html
Labels: enhancement

#625 Release week 48
  .wordlist.txt
  docs/assets/images/dietpi-backup-daily.png
  docs/assets/images/dietpi-backup_1.png
  docs/assets/images/dietpi-dashboard.jpg
  docs/assets/images/dietpi-overclocking-profiles.jpg
  docs/assets/images/dietpi-radxa-zero.jpg
  docs/assets/images/dietpi-raspberry-pi-zero-2.jpg
  docs/assets/images/dietpi-software-cloud-filebrowser.svg
  docs/assets/images/dietpi-version-77.jpg
  docs/assets/stylesheets/custom.css
  docs/hardware.md
  overrides/main.html
  requirements.txt
Labels: release

#630 Description of the usage of dietpi.txt added
  docs/install.md
  docs/usage.md
Labels: extension

#631 Beta release notes 7.9
  docs/assets/images/dietpi-backup-amount.jpg
  docs/assets/images/dietpi-dashboard-login.jpg
  docs/assets/images/dietpi-dashboard-port-change.jpg
  docs/releases.md
  docs/software.md
  docs/software/dns_servers.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/webserver_stack.md
Labels: extension, Next DietPi release

#632 DietPi beta v7.9 release
  docs/assets/images/dietpi-backup-amount.jpg
  docs/assets/images/dietpi-dashboard-login.jpg
  docs/assets/images/dietpi-dashboard-port-change.jpg
  docs/install.md
  docs/releases.md
  docs/software.md
  docs/software/dns_servers.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/webserver_stack.md
  docs/usage.md
Labels: release

#635 Update and align Gitea and Gogs docs
  docs/software/cloud.md
Labels: correction, extension, Next DietPi release

#633 Functional extensions of dietpi-backup described
  docs/assets/images/dietpi-backup_1.png
  docs/dietpi_tools.md
Labels: extension, Next DietPi release

#634 DietPi v7.9 notes
  docs/assets/images/dietpi-software.jpg
  docs/getting_started.md
  docs/releases.md
  docs/software.md
  docs/software/databases.md
Labels: extension, Next DietPi release

#637 DietPi v7.9 release week
  .wordlist.txt
  docs/assets/images/dietpi-backup_1.png
  docs/assets/images/dietpi-software.jpg
  docs/dietpi_tools.md
  docs/getting_started.md
  docs/releases.md
  docs/software.md
  docs/software/cloud.md
  docs/software/databases.md
  docs/software/media.md
Labels: release

#639 Release notes v7.9: New documentation part described
  docs/releases.md
Labels: enhancement

#642 Release week 50
  docs/assets/images/dietpi-backup-amount.jpg
  docs/assets/images/dietpi-backup_1.png
  docs/assets/images/dietpi-dashboard-login.jpg
  docs/assets/images/dietpi-dashboard-port-change.jpg
  docs/assets/images/dietpi-software.jpg
  docs/releases.md
  docs/software/bittorrent.md
  docs/usage.md
Labels: release

#644 Fix AdGuard Home update instructions
  docs/assets/images/adguardhome-update-notification.png
  docs/software/dns_servers.md
Labels: correction

#645 Release week 50
  docs/assets/images/adguardhome-update-notification.png
  docs/assets/images/dietpi-config_camera-activation.png
  docs/software/camera.md
  docs/software/dns_servers.md
Labels: release

#643 Nextcloud: FAQ entry regarding opcache added
  .wordlist.txt
  docs/assets/images/OpCache_php_output.png
  docs/software/cloud.md
Labels: extension

#650 Links to U-labs.de added
  docs/references.md
  docs/usage.md
Labels: extension

#651 Description for Mac OS Parallels Desktop installation added
  docs/assets/images/dietpi-Parallels00.png
  docs/assets/images/dietpi-Parallels01.png
  docs/assets/images/dietpi-Parallels02.png
  docs/assets/images/dietpi-Parallels03.png
  docs/assets/images/dietpi-Parallels04.png
  docs/assets/images/dietpi-Parallels05.png
  docs/assets/images/dietpi-Parallels06.png
  docs/assets/images/dietpi-Parallels07.png
  docs/assets/images/dietpi-Parallels08.png
  docs/assets/images/dietpi-Parallels09.png
  docs/assets/images/dietpi-Parallels10.png
  docs/assets/images/dietpi-Parallels20.png
  docs/assets/images/dietpi-Parallels21.png
  docs/assets/images/dietpi-Parallels22.png
  docs/hardware.md
  docs/install.md
Labels: extension

#653 Fix and align some x86_64 docs parts
  .github/workflows/actions.yml
  docs/install.md
Labels: correction, enhancement
