Repository MichaIng/DietPi-Docs, pull requests merged in 2021-09, with the labels that each got.

#560 Release week 35
  README.md
Labels: release

#561 XFS file system description added
  docs/assets/images/dietpi-drive-manager_7.png
  docs/dietpi_tools.md
Labels: extension

#563 Update VM image downloads and complement RPi variants
  .github/workflows/actions.yml
  .wordlist.txt
  docs/hardware.md
Labels: enhancement, extension

#565 Minor change: Add configuration file name in description
  docs/software/file_servers.md
Labels: enhancement

#566 Update Hyper-V install instructions
  .wordlist.txt
  docs/assets/images/dietpi-HyperV-safe-start.png
  docs/install.md
Labels: correction, enhancement

#567 Release week 36
  .github/workflows/actions.yml
  .wordlist.txt
  docs/assets/images/dietpi-HyperV-safe-start.png
  docs/assets/images/dietpi-drive-manager_7.png
  docs/assets/images/dietpi-version-75-debian11.jpg
  docs/dietpi_tools.md
  docs/hardware.md
  docs/install.md
  docs/software/file_servers.md
Labels: release

#571 Release week 37
  docs/releases.md
Labels: release

#573 Release week 37.2
  .wordlist.txt
  docs/assets/images/dietpi-software-cloud-filebrowser.svg
  docs/releases.md
  docs/software.md
  docs/software/cloud.md
  docs/software/gaming.md
  docs/software/media.md
Labels: release

#574 Link to file-browser corrected
  docs/software.md
  docs/software/cloud.md
Labels: correction

#575 Release week 37.3
  docs/releases.md
  docs/software.md
  docs/software/cloud.md
Labels: release

#579 Add instructions for adding network drives
  docs/dietpi_tools.md
Labels: enhancement

#578 Replace MineOS YouTube video with forum/source/license links
  docs/software/gaming.md
Labels: correction

#580 Release week 38
  docs/dietpi_tools.md
  docs/software/gaming.md
  docs/software/media.md
Labels: release

#582 DietPi-Software | File Browser
  docs/software/cloud.md
Labels: enhancement

#581 False Web-Interface Port given for Snapcast-Server
  docs/software/media.md
Labels: correction

#584 Release week 39
  docs/hardware.md
  docs/releases.md
  docs/software/cloud.md
  docs/software/media.md
  mkdocs.yml
  requirements.txt
Labels: release

#585 update filebrowser
  docs/software/cloud.md
Labels: correction
