Repository MichaIng/DietPi-Docs, pull requests merged in 2021-07, with the labels that each got.

#529 DietPi-Software | MineOS
  docs/software/gaming.md
Labels: correction

#530 Expand release notes 7.3
  .wordlist.txt
  docs/assets/images/dietpi-software-frp.png
  docs/releases.md
  docs/software/advanced_networking.md
  docs/software/media.md
Labels: correction, extension

#533 Release week 28
  .wordlist.txt
  docs/assets/images/dietpi-software-frp.png
  docs/references.md
  docs/releases.md
  docs/socialmedia.md
  docs/software/advanced_networking.md
  docs/software/dns_servers.md
  docs/software/gaming.md
  docs/software/media.md
  mkdocs.yml
Labels: release

#535 Complement Komga logs
  docs/software/media.md
Labels: Next DietPi release, extension

#537 Add description for Synapse and PostgreSQL
  docs/assets/images/dietpi-software-postgresql.png
  docs/software.md
  docs/software/databases.md
  docs/software/hardware_projects.md
  docs/software/social.md
Labels: Next DietPi release, new content

#539 Release week 29 (DietPi v7.4)
  docs/assets/images/dietpi-software-postgresql.png
  docs/releases.md
  docs/software.md
  docs/software/databases.md
  docs/software/hardware_projects.md
  docs/software/media.md
  docs/software/social.md
Labels: release

#542 small updates to release notes 7.4
  .wordlist.txt
  docs/releases.md
  docs/software.md
  docs/software/bittorrent.md
Labels: enhancement, extension
