Repository MichaIng/DietPi-Docs, pull requests merged in 2022-11, with the labels that each got.

#784 Created homepages page + homer documentation
  docs/assets/images/homer-config.png
  docs/assets/images/homer-preview.png
  docs/software/system_stats.md
Labels: extension

#787 Homer documentation beautification
  .wordlist.txt
  docs/software.md
  docs/software/system_stats.md
Labels: correction, enhancement

#791 Small info about HACS added
  docs/software/home_automation.md
Labels: enhancement

#786 Relnotes v8.11, 1st step
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_11.jpg
  docs/releases.md
  docs/releases/v8_11.md
  mkdocs.yml
Labels: release

#789 Change Remot3.it -> Remote.It
  docs/assets/images/dietpi-software-remotedesktop-remoteit.png
  docs/software.md
  docs/software/remote_desktop.md
Labels: correction

#792 Release week 46
  .github/workflows/main.yml
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_11.jpg
  docs/assets/images/dietpi-software-remotedesktop-remoteit.png
  docs/assets/images/homer-preview.png
  docs/hardware.md
  docs/releases.md
  docs/releases/v6_27.md
  docs/releases/v6_32.md
  docs/releases/v7_0.md
  docs/releases/v7_7.md
  docs/releases/v8_11.md
  docs/releases/v8_3.md
  docs/releases/v8_4.md
  docs/releases/v8_7.md
  docs/releases/v8_9.md
  docs/software.md
  docs/software/home_automation.md
  docs/software/remote_desktop.md
  docs/software/system_stats.md
  docs/software/vpn.md
  mkdocs.yml
Labels: release

#793 Add link to Homer docs
  docs/releases/v8_11.md
Labels: correction

#799 Release week 47
  docs/assets/images/dietpi-login01.jpg
  docs/assets/images/dietpi-release-v8_10.jpg
  docs/assets/images/dietpi-release-v8_11.jpg
  docs/assets/images/homer-preview.png
  docs/install.md
  docs/releases/v8_11.md
  docs/software/cloud.md
  docs/usage.md
Labels: correction, enhancement

#801 Software Homer: Text beautification
  docs/references.md
  docs/software/system_stats.md
Labels: enhancement
