Repository MichaIng/DietPi-Docs, pull requests merged in 2022-02, with the labels that each got.

#679 Update Jellyfin port + alignments
  docs/software/databases.md
  docs/software/hardware_projects.md
  docs/software/media.md
Labels: correction, enhancement, Next DietPi release

#678 Ampache: Added mount hints for Samba shares
  docs/software/media.md
Labels: enhancement, Next DietPi release

#682 Add DietPi v8.1 release notes
  .wordlist.txt
  docs/releases.md
  docs/releases/v7_1.md
  docs/releases/v7_2.md
  docs/releases/v7_3.md
  docs/releases/v7_4.md
  docs/releases/v7_5.md
  docs/releases/v7_6.md
  docs/releases/v7_7.md
  docs/releases/v7_8.md
  docs/releases/v7_9.md
  docs/releases/v8_0.md
  docs/releases/v8_1.md
Labels: extension, Next DietPi release

#681 Release week 5
  .github/workflows/actions.yml
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_1.jpg
  docs/releases.md
  docs/releases/v7_1.md
  docs/releases/v7_2.md
  docs/releases/v7_3.md
  docs/releases/v7_4.md
  docs/releases/v7_5.md
  docs/releases/v7_6.md
  docs/releases/v7_7.md
  docs/releases/v7_8.md
  docs/releases/v7_9.md
  docs/releases/v8_0.md
  docs/releases/v8_1.md
  docs/software.md
  docs/software/databases.md
  docs/software/hardware_projects.md
  docs/software/media.md
  docs/software/social.md
  mkdocs.yml
Labels: release, Next DietPi release

#689 MinIO | Fix default login credentials
  docs/software/cloud.md
Labels: correction

#684 Description for UTM virtual machines added
  .wordlist.txt
  docs/assets/images/UTM1.png
  docs/assets/images/UTM2.png
  docs/assets/images/UTM3.png
  docs/assets/images/UTM4.png
  docs/hardware.md
  docs/install.md
Labels: new content, Next DietPi release

#690 Release week 6
  .wordlist.txt
  docs/assets/images/UTM1.png
  docs/assets/images/UTM2.png
  docs/assets/images/UTM3.png
  docs/assets/images/UTM4.png
  docs/assets/images/airsonic_setup_4.png
  docs/hardware.md
  docs/install.md
  docs/releases/v8_1.md
  docs/software/cloud.md
  docs/software/media.md
Labels: release

#693 Title description (meta tags) added
  docs/dietpi_tools.md
  docs/hardware.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/databases.md
  docs/software/desktop.md
  docs/software/distributed_projects.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/ssh.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
Labels: meta

#694 Text beautification
  .wordlist.txt
  docs/dietpi_tools.md
Labels: enhancement

#683 Added documentation for MicroK8s
  docs/assets/images/microk8s.png
  docs/software.md
  docs/software/system_stats.md
Labels: extension, Next DietPi release

#696 Fix and complement Tautulli docs
  .wordlist.txt
  docs/software/media.md
  docs/software/system_stats.md
Labels: correction, extension

#697 Update Docker Compose docs
  docs/software/programming.md
Labels: correction, Next DietPi release

#698 Update Roon docs for DietPi v8.2
  docs/software/media.md
Labels: correction, extension, Next DietPi release
