Repository MichaIng/DietPi-Docs, pull requests merged in 2022-12, with the labels that each got.

#803 DietPi-Backup - space check option described
  docs/assets/images/dietpi-backup_1.png
  docs/dietpi_tools.md
Labels: enhancement

#808 New hardware NanoPi R6S added
  docs/hardware.md
Labels: extension

#804 New hardware ROCK 5B added
  docs/hardware.md
Labels: extension

#807 Releasenotes v8.12 & RPi camera web interface
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_12.jpg
  docs/releases.md
  docs/releases/v8_12.md
  docs/software.md
  docs/software/camera.md
  docs/software/databases.md
  docs/software/programming.md
  mkdocs.yml
Labels: release

#809 Release week 50
  .github/workflows/main.yml
  .wordlist.txt
  docs/assets/images/dietpi-backup_1.png
  docs/assets/images/dietpi-release-v8_12.jpg
  docs/assets/images/dietpi-software-sshserver-dropbear.jpg
  docs/dietpi_tools.md
  docs/hardware.md
  docs/references.md
  docs/releases.md
  docs/releases/v8_12.md
  docs/software.md
  docs/software/camera.md
  docs/software/databases.md
  docs/software/programming.md
  docs/software/system_stats.md
  mkdocs.yml
Labels: release

#810 DietPi-Software | myMPD: Update docs for DietPi v8.12
  docs/software/media.md
Labels: correction

#811 Media systems minor enhancements (screenshots, hints)
  docs/assets/images/dietpi-software-media-mopidy.png
  docs/assets/images/dietpi-software-media-mympd.gif
  docs/assets/images/dietpi-software-media-mympd.png
  docs/assets/images/dietpi-software-media-ompd-update.png
  docs/assets/images/dietpi-software-media-ompd.png
  docs/software.md
  docs/software/media.md
Labels: enhancement

#815 Images optimized
  docs/assets/images/UTM1.png
  docs/assets/images/dietpi-software-cloud-nextcloudtalk.png
  docs/assets/images/dietpi-software-media-mopidy.png
  docs/assets/images/dietpi-software-media-mympd.png
  docs/assets/images/dietpi-software-media-ompd-update.png
  docs/assets/images/dietpi-software-media-ompd.png
  docs/assets/images/dietpi-software-systemstat-cloudshell-touchscreensupport.jpg
  docs/assets/images/dietpi-software-systemstat-cloudshell-wavesharesupport.png
  docs/assets/images/homer-preview.png
  docs/software/media.md
Labels: enhancement

#817 DietPi-Sync and DietPi-Backup descriptions extended
  docs/assets/images/dietpi-sync-dryrun.png
  docs/dietpi_tools.md
Labels: extension
