Repository MichaIng/DietPi-Docs, pull requests merged in 2022-07, with the labels that each got.

#737 Added Tailscale docs
  .wordlist.txt
  docs/assets/images/tailscale-logo.svg
  docs/software.md
  docs/software/vpn.md
Labels: extension, Next DietPi release

#738 Rclone Docs
  .wordlist.txt
  docs/assets/images/rclone-logo.svg
  docs/software.md
  docs/software/cloud.md
  docs/software/vpn.md
Labels: extension, Next DietPi release

#745 Added documentation for Prometheus Node Exporter
  docs/assets/images/grafana_node_exporter_full.png
  docs/software.md
  docs/software/system_stats.md
Labels: extension, Next DietPi release

#746 Release week 26
  .github/dependabot.yml
  .github/workflows/actions.yml
  .wordlist.txt
  docs/assets/images/grafana_node_exporter_full.png
  docs/assets/images/rclone-logo.svg
  docs/assets/images/tailscale-logo.svg
  docs/assets/images/zerotier-logo.png
  docs/software.md
  docs/software/advanced_networking.md
  docs/software/cloud.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/usage.md
Labels: release, Next DietPi release

#748 Releasenotes v8.6
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_6.jpg
  docs/releases.md
  docs/releases/v8_6.md
  mkdocs.yml
Labels: extension, Next DietPi release

#749 Quartz64 added
  docs/hardware.md
Labels: extension, Next DietPi release

#750 Added PiVPN unattended installation option, Youtube video link added for Tailscale
  docs/software/vpn.md
Labels: enhancement, extension

#751 Fix Chromium GPU link
  docs/software/desktop.md
Labels: correction

#752 Release week 26.2
  .github/workflows/actions.yml
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_6.jpg
  docs/hardware.md
  docs/releases.md
  docs/releases/v8_6.md
  docs/software/desktop.md
  docs/software/vpn.md
  docs/usage.md
  mkdocs.yml
Labels: release

#757 Update LMS and Squeezelite docs (#753)
  .github/workflows/actions.yml
  .wordlist.txt
  docs/software/desktop.md
  docs/software/media.md
Labels: release

#761 DietPi-Software | Navidrome
  .wordlist.txt
  docs/assets/images/dietpi-software-media-navidrome.png
  docs/software.md
  docs/software/media.md
Labels: new content, Next DietPi release

#762 DietPi-Software | Readarr
  docs/assets/images/dietpi-software-download-readarr.png
  docs/assets/images/dietpi-software-download-readarrpermissions.png
  docs/software.md
  docs/software/bittorrent.md
Labels: new content, Next DietPi release

#759 Releasenotes v8.7
  .github/workflows/actions.yml
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_7.jpg
  docs/hardware.md
  docs/releases.md
  docs/releases/v8_7.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/databases.md
  docs/software/media.md
  docs/software/programming.md
  docs/software/social.md
  docs/software/webserver_stack.md
  docs/usage.md
  mkdocs.yml
Labels: extension, Next DietPi release

#763 Release week 30
  .github/workflows/actions.yml
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_7.jpg
  docs/assets/images/dietpi-software-download-readarr.png
  docs/assets/images/dietpi-software-download-readarrpermissions.png
  docs/assets/images/dietpi-software-media-navidrome.png
  docs/hardware.md
  docs/releases.md
  docs/releases/v8_7.md
  docs/software.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/databases.md
  docs/software/media.md
  docs/software/programming.md
  docs/software/social.md
  docs/software/webserver_stack.md
  docs/usage.md
  mkdocs.yml
Labels: release

#764 Add missing v8.7 release note entries
  .wordlist.txt
  docs/releases/v8_7.md
Labels: release
