Repository MichaIng/DietPi-Docs, pull requests merged in 2022-09, with the labels that each got.

#774 Added small hint for VirtualHere regarding X11 GUI
  docs/software/programming.md
  docs/software/remote_desktop.md
Labels: extension

#773 Update go docs
  docs/software/programming.md
Labels: correction

#775 fix link to automatic base installation
  docs/install.md
Labels: correction

#777 Release week 38 (DietPi v8.9)
  .wordlist.txt
  docs/assets/images/dietpi-backup_filter-option.jpg
  docs/assets/images/dietpi-release-v8_6.jpg
  docs/assets/images/dietpi-release-v8_7.jpg
  docs/assets/images/dietpi-release-v8_8.jpg
  docs/assets/images/dietpi-release-v8_9.jpg
  docs/assets/images/dietpi-software-download-readarr.png
  docs/assets/images/dietpi-software-download-readarrpermissions.png
  docs/assets/images/dietpi-software-media-navidrome.png
  docs/assets/images/grafana_node_exporter_full.png
  docs/assets/images/zerotier-logo.png
  docs/dietpi_tools.md
  docs/hardware.md
  docs/install.md
  docs/releases.md
  docs/releases/v6_34.md
  docs/releases/v8_9.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/webserver_stack.md
  mkdocs.yml
Labels: release
