Repository MichaIng/DietPi-Docs, pull requests merged in 2022-03, with the labels that each got.

#700 Add Proxmox install docs
  .wordlist.txt
  docs/assets/images/proxmox-logo.svg
  docs/assets/images/proxmox1.png
  docs/assets/images/proxmox2.png
  docs/assets/images/proxmox3.png
  docs/hardware.md
  docs/install.md
Labels: extension

#701 Added description for ESXi Hypervisor
  .wordlist.txt
  docs/assets/images/VMwareESXi_01.jpg
  docs/assets/images/VMwareESXi_02.jpg
  docs/assets/images/VMwareESXi_03.jpg
  docs/assets/images/VMwareESXi_04.jpg
  docs/assets/images/VMwareESXi_05.jpg
  docs/hardware.md
  docs/install.md
Labels: new content, Next DietPi release

#692 Preliminary start with v8.2 release notes
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_2.jpg
  docs/releases.md
  docs/releases/v8_2.md
  docs/software.md
  mkdocs.yml
Labels: Next DietPi release

#699 Release week 9
  .gitignore
  .wordlist.txt
  docs/assets/images/VMwareESXi_01.jpg
  docs/assets/images/VMwareESXi_02.jpg
  docs/assets/images/VMwareESXi_03.jpg
  docs/assets/images/VMwareESXi_04.jpg
  docs/assets/images/VMwareESXi_05.jpg
  docs/assets/images/dietpi-release-v8_2.jpg
  docs/assets/images/microk8s.png
  docs/assets/images/proxmox-logo.svg
  docs/assets/images/proxmox1.png
  docs/assets/images/proxmox2.png
  docs/assets/images/proxmox3.png
  docs/assets/stylesheets/custom.css
  docs/dietpi_tools.md
  docs/hardware.md
  docs/install.md
  docs/releases.md
  docs/releases/v8_2.md
  docs/software.md
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/databases.md
  docs/software/desktop.md
  docs/software/distributed_projects.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/ssh.md
  docs/software/system_security.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
  mkdocs.yml
Labels: release

#706 Added reboot message dialog
  docs/assets/images/dietpi-banner-reboot.jpg
  docs/releases/v8_2.md
Labels: enhancement

#704 Release week 11
  .github/workflows/actions.yml
  .wordlist.txt
  docs/assets/images/dietpi-banner-reboot.jpg
  docs/releases/v8_2.md
  docs/software/cloud.md
Labels: release

#707 Added trial information to VirtualHere
  docs/software/remote_desktop.md
Labels: enhancement

#709 CI | Add lychee cache
  .github/workflows/actions.yml
  docs/assets/images/dietpi-software-webstack-redis.svg
  docs/assets/images/redis-logo.svg
  docs/software/databases.md
Labels: meta
