Repository MichaIng/DietPi-Docs, pull requests merged in 2022-01, with the labels that each got.

#654 Release notes (January 2022)
  .wordlist.txt
  docs/assets/images/dietpi-version-80.jpg
  docs/releases.md
  docs/releases/v6_27.md
  docs/releases/v6_28.md
  docs/releases/v6_29.md
  docs/releases/v6_30.md
  docs/releases/v6_31.md
  docs/releases/v6_32.md
  docs/releases/v6_33.md
  docs/releases/v6_34.md
  docs/releases/v7_0.md
  docs/releases/v7_1.md
  docs/releases/v7_2.md
  docs/releases/v7_3.md
  docs/releases/v7_4.md
  docs/releases/v7_5.md
  docs/releases/v7_6.md
  docs/releases/v7_7.md
  docs/releases/v7_8.md
  docs/releases/v7_9.md
  docs/releases/v8_0.md
  mkdocs.yml
Labels: release

#660 Changed Parallels Desktop installation description
  docs/assets/images/dietpi-Parallels00.png
  docs/assets/images/dietpi-Parallels01.png
  docs/assets/images/dietpi-Parallels02.png
  docs/assets/images/dietpi-Parallels03.png
  docs/assets/images/dietpi-Parallels04.png
  docs/assets/images/dietpi-Parallels06.png
  docs/assets/images/dietpi-Parallels08.png
  docs/assets/images/dietpi-Parallels09.png
  docs/assets/images/dietpi-Parallels20.png
  docs/assets/images/dietpi-Parallels21.png
  docs/assets/images/dietpi-Parallels22.png
  docs/hardware.md
  docs/install.md
Labels: new content

#661 Releasenotes: VM Parallels added
  docs/releases/v8_0.md
Labels: enhancement

#658 Release week 1
  .github/workflows/actions.yml
  .wordlist.txt
  docs/assets/images/OpCache_php_output.png
  docs/assets/images/Parallels1.jpg
  docs/assets/images/Parallels2.png
  docs/assets/images/Parallels3.png
  docs/assets/images/adguardhome-update-notification.png
  docs/assets/images/dietpi-config_camera-activation.png
  docs/assets/images/dietpi-version-80.jpg
  docs/hardware.md
  docs/install.md
  docs/references.md
  docs/releases.md
  docs/releases/v6_27.md
  docs/releases/v6_28.md
  docs/releases/v6_29.md
  docs/releases/v6_30.md
  docs/releases/v6_31.md
  docs/releases/v6_32.md
  docs/releases/v6_33.md
  docs/releases/v6_34.md
  docs/releases/v7_0.md
  docs/releases/v7_1.md
  docs/releases/v7_2.md
  docs/releases/v7_3.md
  docs/releases/v7_4.md
  docs/releases/v7_5.md
  docs/releases/v7_6.md
  docs/releases/v7_7.md
  docs/releases/v7_8.md
  docs/releases/v7_9.md
  docs/releases/v8_0.md
  docs/software/cloud.md
  docs/usage.md
  mkdocs.yml
Labels: release

#662 (German) links beautification
  docs/dietpi_tools.md
  docs/install.md
  docs/references.md
  docs/software/cloud.md
  docs/software/dns_servers.md
  docs/software/home_automation.md
  docs/software/vpn.md
  docs/usage.md
Labels: correction

#663 Fix v8.0 GitHub link
  docs/dietpi_tools.md
  docs/install.md
  docs/references.md
  docs/releases/v8_0.md
  docs/software/cloud.md
  docs/software/dns_servers.md
  docs/software/home_automation.md
  docs/software/vpn.md
  docs/usage.md
Labels: release

#665 Update Blynk Server docs
  docs/software/hardware_projects.md
Labels: correction, extension

#664 Complement v8.0 release notes
  .wordlist.txt
  docs/assets/images/dietpi-banner_large_hostname.png
  docs/releases/v8_0.md
Labels: extension

#666 Update FuguHub docs
  docs/software/cloud.md
Labels: correction

#667 Add DietPi-Dashboard docs about backend-only/multi-node setup
  .wordlist.txt
  docs/software/system_stats.md
Labels: extension

#668 Extend Airsonic docs
  docs/assets/images/airsonic-logo.svg
  docs/assets/images/airsonic_setup_1.png
  docs/assets/images/airsonic_setup_2.png
  docs/assets/images/airsonic_setup_3.png
  docs/assets/images/airsonic_setup_4.png
  docs/assets/images/dietpi-software-media-airsonic.png
  docs/software.md
  docs/software/media.md
Labels: correction, extension

#670 Typo in Dashboard admonition
  docs/software/system_stats.md
Labels: correction

#669 Release week 1 batch 2
  .wordlist.txt
  docs/assets/images/airsonic-logo.svg
  docs/assets/images/airsonic_setup_1.png
  docs/assets/images/airsonic_setup_2.png
  docs/assets/images/airsonic_setup_3.png
  docs/assets/images/airsonic_setup_4.png
  docs/assets/images/dietpi-banner_large_hostname.png
  docs/assets/images/dietpi-software-media-airsonic.png
  docs/hardware.md
  docs/releases/v8_0.md
  docs/software.md
  docs/software/cloud.md
  docs/software/hardware_projects.md
  docs/software/media.md
  docs/software/system_stats.md
Labels: release

#671 Release week 2
  .github/workflows/actions.yml
  docs/usage.md
Labels: release

#672 Add info for DietPi-Dashboard
  docs/software/system_stats.md
Labels: enhancement

#673 Buster upgrade | Add Python 3 upgrade step
  docs/usage.md
Labels: extension

#674 Release week 3
  .github/workflows/actions.yml
  docs/software/system_stats.md
  docs/usage.md
Labels: release

#676 Add meaningful title and description meta tags
  .github/workflows/actions.yml
  docs/getting_started.md
  docs/index.md
  docs/install.md
  docs/references.md
  docs/releases.md
  docs/socialmedia.md
  docs/software.md
Labels: enhancement

#677 Release week 4
  .github/workflows/actions.yml
  docs/dietpi_tools.md
  docs/getting_started.md
  docs/index.md
  docs/install.md
  docs/references.md
  docs/releases.md
  docs/socialmedia.md
  docs/software.md
Labels: release
