Repository MichaIng/DietPi-Docs, pull requests merged in 2023-12, with the labels that each got.

#954 Update Ampache docs
  docs/software/media.md
Labels: Next DietPi release, update

#957 NZBGet | All logs are done to journal now
  docs/software/bittorrent.md
Labels: Next DietPi release

#958 Missing internal git link added and cross linking gitea/gogs
  docs/software.md
  docs/software/cloud.md
  docs/software/programming.md
Labels: correction

#959 Releasenotes v8.25 and new hardware
  .wordlist.txt
  docs/assets/images/PINE64-STAR64.jpg
  docs/assets/images/dietpi-release-v8_25.jpg
  docs/hardware.md
  docs/releases.md
  docs/releases/v8_25.md
  mkdocs.yml
Labels: release

#960 Release week 51
  .github/workflows/main.yml
  .wordlist.txt
  README.md
  docs/assets/images/PINE64-STAR64.jpg
  docs/assets/images/dietpi-release-v8_25.jpg
  docs/assets/images/dietpi-software-programming-git.svg
  docs/dietpi_tools.md
  docs/hardware.md
  docs/releases.md
  docs/releases/v8_24.md
  docs/releases/v8_25.md
  docs/software.md
  docs/software/bittorrent.md
  docs/software/cloud.md
  docs/software/desktop.md
  docs/software/media.md
  docs/software/programming.md
  mkdocs.yml
Labels: release

#961 Update WSDD docs
  .wordlist.txt
  docs/software/cloud.md
  docs/software/file_servers.md
  docs/software/programming.md
Labels: correction

#962 Update social.md
  docs/software/social.md
Labels: correction
