Repository MichaIng/DietPi-Docs, pull requests merged in 2023-11, with the labels that each got.

#945 Release week 44
  .github/workflows/main.yml
  docs/hardware.md
  docs/index.md
Labels: release

#947 Release week 46
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_22.jpg
  docs/assets/images/dietpi-release-v8_23.jpg
  docs/assets/images/dietpi-release-v8_24.jpg
  docs/install.md
  docs/releases.md
  docs/releases/v8_24.md
  docs/software/bittorrent.md
  docs/software/gaming.md
Labels: release

#955 Bugfix openHAB link
  docs/releases/v8_24.md
Labels: correction

#952 added git
  docs/assets/images/dietpi-software-programming-git.svg
  docs/software/programming.md
Labels: extension
