Repository MichaIng/DietPi-Docs, pull requests merged in 2023-03, with the labels that each got.

#856 Added description for Java and Mono, added some Go and Python info
  .wordlist.txt
  docs/assets/images/dietpi-software-programming-java.svg
  docs/assets/images/dietpi-software-programming-mono.png
  docs/software.md
  docs/software/programming.md
Labels: extension

#854 Add StarFive VisionFive 2 hardware
  .wordlist.txt
  docs/assets/images/riscv-starfive-visionfive2.jpg
  docs/hardware.md
Labels: extension

#858 WordPress: Hint for initial dialog added
  docs/assets/images/dietpi-software-social-wordpress-initialdialog.jpg
  docs/software/social.md
Labels: enhancement

#857 Release week 10
  .github/workflows/main.yml
  .wordlist.txt
  docs/assets/images/dietpi-software-programming-java.svg
  docs/assets/images/dietpi-software-programming-mono.png
  docs/assets/images/dietpi-software-social-wordpress-initialdialog.jpg
  docs/assets/images/riscv-starfive-visionfive2.jpg
  docs/hardware.md
  docs/software.md
  docs/software/programming.md
  docs/software/social.md
Labels: release

#859 Release notes v8.15 (#855)
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_15.jpg
  docs/releases.md
  docs/releases/v6_27.md
  docs/releases/v8_15.md
  mkdocs.yml
Labels: release

#862 [Improvement] Add website link for Baïkal
  docs/software/social.md
Labels: extension

#864 Update Parallels install instructions for VMX appliacance
  docs/hardware.md
  docs/install.md
Labels: correction

#865 Release week 12
  .github/workflows/main.yml
  docs/assets/images/dietpi-release-v8_15.jpg
  docs/assets/images/dietpi-software-programming-java.svg
  docs/assets/images/dietpi-software-programming-mono.png
  docs/assets/images/dietpi-software-social-wordpress-initialdialog.jpg
  docs/hardware.md
  docs/install.md
  docs/software/social.md
Labels: release
