Repository MichaIng/DietPi-Docs, pull requests merged in 2023-04, with the labels that each got.

#871 Extend Pi-Hole documentation
  .wordlist.txt
  docs/software/dns_servers.md
Labels: extension

#870 Releasenotes v8.16 and microblog.pub documentation
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_16.jpg
  docs/assets/images/dietpi-software-social-microblogpub1.jpg
  docs/assets/images/dietpi-software-social-microblogpub2.jpg
  docs/releases.md
  docs/releases/v8_1.md
  docs/releases/v8_16.md
  docs/software.md
  docs/software/social.md
  mkdocs.yml
Labels: new content, release

#872 Easter release week (release v8.16)
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_16.jpg
  docs/assets/images/dietpi-software-social-microblogpub1.jpg
  docs/assets/images/dietpi-software-social-microblogpub2.jpg
  docs/releases.md
  docs/releases/v8_1.md
  docs/releases/v8_16.md
  docs/software.md
  docs/software/dns_servers.md
  docs/software/home_automation.md
  docs/software/media.md
  docs/software/social.md
  mkdocs.yml
Labels: release

#875 Fix several links in release notes
  docs/references.md
  docs/releases/v6_27.md
  docs/releases/v6_29.md
  docs/releases/v6_30.md
  docs/releases/v6_31.md
  docs/releases/v6_33.md
  docs/releases/v6_34.md
  docs/releases/v7_0.md
  docs/releases/v7_1.md
  docs/releases/v7_2.md
  docs/releases/v7_3.md
  docs/releases/v7_5.md
  docs/releases/v7_7.md
  docs/releases/v7_8.md
  docs/releases/v7_9.md
  docs/releases/v8_1.md
  docs/releases/v8_15.md
  docs/releases/v8_16.md
  docs/releases/v8_2.md
  docs/releases/v8_3.md
  docs/releases/v8_8.md
Labels: correction

#874 Description of automated restore via dietpi.txt added
  docs/dietpi_tools/system_maintenance.md
  docs/usage.md
Labels: extension

#877 Use of NFS mount for remote backup locations added
  docs/dietpi_tools/system_maintenance.md
Labels: extension

#879 Release week 17
  docs/dietpi_tools/system_maintenance.md
  docs/references.md
  docs/releases/v6_27.md
  docs/releases/v6_29.md
  docs/releases/v6_30.md
  docs/releases/v6_31.md
  docs/releases/v6_33.md
  docs/releases/v6_34.md
  docs/releases/v7_0.md
  docs/releases/v7_1.md
  docs/releases/v7_2.md
  docs/releases/v7_3.md
  docs/releases/v7_5.md
  docs/releases/v7_7.md
  docs/releases/v7_8.md
  docs/releases/v7_9.md
  docs/releases/v8_1.md
  docs/releases/v8_15.md
  docs/releases/v8_16.md
  docs/releases/v8_2.md
  docs/releases/v8_3.md
  docs/releases/v8_8.md
  docs/software/dns_servers.md
  docs/software/hardware_projects.md
  docs/usage.md
Labels: release

#882 Rename NanoPi R6S to R6S/R6C
  docs/hardware.md
Labels: correction, release
