Repository MichaIng/DietPi-Docs, pull requests merged in 2023-01, with the labels that each got.

#818 UrBackup: Added info about configuration
  .github/workflows/main.yml
  .wordlist.txt
  docs/install.md
  docs/software/cloud.md
Labels: extension

#824 Release week 01/2023
  .github/workflows/main.yml
  .wordlist.txt
  docs/assets/images/UTM1.png
  docs/assets/images/dietpi-backup_1.png
  docs/assets/images/dietpi-software-cloud-nextcloudtalk.png
  docs/assets/images/dietpi-software-media-mopidy.png
  docs/assets/images/dietpi-software-media-mympd.gif
  docs/assets/images/dietpi-software-media-mympd.png
  docs/assets/images/dietpi-software-media-ompd-update.png
  docs/assets/images/dietpi-software-media-ompd.png
  docs/assets/images/dietpi-software-systemstat-cloudshell-touchscreensupport.jpg
  docs/assets/images/dietpi-software-systemstat-cloudshell-wavesharesupport.png
  docs/assets/images/dietpi-sync-dryrun.png
  docs/assets/images/homer-preview.png
  docs/dietpi_tools.md
  docs/hardware.md
  docs/install.md
  docs/software.md
  docs/software/cloud.md
  docs/software/media.md
  docs/software/webserver_stack.md
Labels: release

#825 Samba: Describe wsdd (Web Service Dynamic Discovery)
  docs/software/file_servers.md
Labels: extension

#827 Start of wsdd service added to description of wsdd installation
  docs/software/file_servers.md
Labels: enhancement

#628 Enable new tabs style with scroll buttons
  .spellcheck.yml
  docs/assets/stylesheets/custom.css
  mkdocs.yml
  requirements.txt
Labels: enhancement

#828 Enhance Nextcloud brute-force protection docs
  .wordlist.txt
  docs/software/cloud.md
  docs/software/system_security.md
Labels: correction, enhancement

#829 Homer: Wrong capitalization lead to copy error when trying to apply MacOS theme.
  docs/software/system_stats.md
Labels: correction

#826 Releasenotes v8.13 and minor bugfix RN v8.9
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_13.jpg
  docs/releases.md
  docs/releases/v8_13.md
  docs/releases/v8_9.md
  mkdocs.yml
Labels: release

#832 Release week 2
  .spellcheck.yml
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_13.jpg
  docs/assets/stylesheets/custom.css
  docs/releases.md
  docs/releases/v8_13.md
  docs/releases/v8_9.md
  docs/software/cloud.md
  docs/software/file_servers.md
  docs/software/system_security.md
  docs/software/system_stats.md
  mkdocs.yml
  requirements.txt
Labels: release

#834 Info about Proxmox installation script added
  docs/install.md
Labels: enhancement

#836 update desktop.rm
  docs/software/desktop.md
Labels: correction

#835 Add orange pi 5 docs
  .wordlist.txt
  docs/assets/images/dietpi-orange-pi-5.png
  docs/hardware.md
Labels: extension

#837 Fix wrong HTTPS port
  docs/dietpi_tools.md
Labels: correction
