Repository MichaIng/DietPi-Docs, pull requests merged in 2023-05, with the labels that each got.

#881 openHAB docu added
  .wordlist.txt
  docs/assets/images/dietpi-software-homeautomation-openhab.jpg
  docs/software.md
  docs/software/home_automation.md
Labels: new content

#883 Releasenotes v8.17
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_17.jpg
  docs/releases.md
  docs/releases/v8_16.md
  docs/releases/v8_17.md
  mkdocs.yml
Labels: extension

#880 DietPi-Docs | Restic: is a fast and secure backup program
  .wordlist.txt
  docs/assets/images/restic-logo.png
  docs/software/cloud.md
Labels: extension

#887 Release week 18
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_16.jpg
  docs/assets/images/dietpi-release-v8_17.jpg
  docs/assets/images/dietpi-software-homeautomation-openhab.jpg
  docs/assets/images/dietpi-software-social-microblogpub1.jpg
  docs/assets/images/dietpi-software-social-microblogpub2.jpg
  docs/assets/images/restic-logo.png
  docs/releases.md
  docs/releases/v8_16.md
  docs/releases/v8_17.md
  docs/software.md
  docs/software/cloud.md
  docs/software/gaming.md
  docs/software/home_automation.md
  mkdocs.yml
Labels: release

#889 Update cloud.md - Urbackup typo
  docs/software/cloud.md
Labels: correction
