Repository MichaIng/DietPi-Docs, pull requests merged in 2023-02, with the labels that each got.

#838 Fix WordPress letter casing
  .wordlist.txt
  docs/releases/v6_32.md
  docs/software.md
  docs/software/social.md
  docs/software/webserver_stack.md
Labels: correction

#833 Move DietPi Tools to an own heading area
  .github/workflows/main.yml
  .wordlist.txt
  docs/dietpi_tools.md
  docs/dietpi_tools/misc_tools.md
  docs/dietpi_tools/software_installation.md
  docs/dietpi_tools/system_configuration.md
  docs/dietpi_tools/system_maintenance.md
  mkdocs.yml
Labels: enhancement, extension

#841 Changes to DietPi-Config docu
  docs/dietpi_tools/system_configuration.md
Labels: correction, extension

#842 Some links to DietPi-Tools updated
  docs/getting_started.md
  docs/install.md
Labels: correction

#843 Add hint to solve RDP connection black screen
  docs/software/remote_desktop.md
Labels: enhancement

#844 Description of Chromium kiosk mode added
  docs/assets/images/dietpi-software-desktop-chromium-kiosk-mode.jpg
  docs/software/desktop.md
Labels: extension

#849 Releasenotes v8.14: Credits for doc added
  docs/releases/v8_14.md
Labels: extension, Next DietPi release

#847 Release week 6
  .github/workflows/main.yml
  .wordlist.txt
  docs/assets/images/dietpi-orange-pi-5.png
  docs/assets/images/dietpi-release-v8_13.jpg
  docs/assets/images/dietpi-release-v8_14.jpg
  docs/assets/images/dietpi-software-desktop-chromium-kiosk-mode.jpg
  docs/assets/images/dietpi-sync-dryrun.png
  docs/dietpi_tools.md
  docs/dietpi_tools/misc_tools.md
  docs/dietpi_tools/software_installation.md
  docs/dietpi_tools/system_configuration.md
  docs/dietpi_tools/system_maintenance.md
  docs/getting_started.md
  docs/hardware.md
  docs/install.md
  docs/releases.md
  docs/releases/v6_32.md
  docs/releases/v8_10.md
  docs/releases/v8_11.md
  docs/releases/v8_12.md
  docs/releases/v8_13.md
  docs/releases/v8_14.md
  docs/software.md
  docs/software/desktop.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/webserver_stack.md
  mkdocs.yml
Labels: release

#851 Release week 6, now as merge commit
  .github/workflows/main.yml
  .wordlist.txt
  docs/assets/images/dietpi-orange-pi-5.png
  docs/assets/images/dietpi-release-v8_13.jpg
  docs/assets/images/dietpi-release-v8_14.jpg
  docs/assets/images/dietpi-software-desktop-chromium-kiosk-mode.jpg
  docs/assets/images/dietpi-sync-dryrun.png
  docs/dietpi_tools.md
  docs/dietpi_tools/misc_tools.md
  docs/dietpi_tools/software_installation.md
  docs/dietpi_tools/system_configuration.md
  docs/dietpi_tools/system_maintenance.md
  docs/getting_started.md
  docs/hardware.md
  docs/install.md
  docs/releases.md
  docs/releases/v6_32.md
  docs/releases/v8_10.md
  docs/releases/v8_11.md
  docs/releases/v8_12.md
  docs/releases/v8_13.md
  docs/releases/v8_14.md
  docs/software.md
  docs/software/desktop.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/webserver_stack.md
  mkdocs.yml
Labels: release

#852 Re-add copy code button to code fences
  mkdocs.yml
Labels: enhancement
