Repository MichaIng/DietPi-Docs, pull requests merged in 2023-08, with the labels that each got.

#912 Minor DoT text explanation added
  docs/software/dns_servers.md
Labels: enhancement

#913 Installation instructions changed from Bullseye to Bookworm
  docs/install.md
Labels: enhancement

#914 WiFi hotspot setting description enhanced (lease time)
  docs/software/advanced_networking.md
Labels: enhancement

#916 MediaWiki moved from cloud to social
  docs/dietpi_tools.md
  docs/hardware.md
  docs/software.md
  docs/software/cloud.md
  docs/software/social.md
Labels: enhancement

#917 Releasenotes v8.21
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_21.jpg
  docs/hardware.md
  docs/releases.md
  docs/releases/v8_21.md
  mkdocs.yml
Labels: release

#918 Release week 34
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_20.jpg
  docs/assets/images/dietpi-release-v8_21.jpg
  docs/assets/images/dietpi-software-advanced-networking-wifihotspot-address-setting.png
  docs/assets/images/dietpi-software-homeautomation-homebridge.svg
  docs/dietpi_tools.md
  docs/hardware.md
  docs/install.md
  docs/releases.md
  docs/releases/v7_1.md
  docs/releases/v8_11.md
  docs/releases/v8_21.md
  docs/software.md
  docs/software/advanced_networking.md
  docs/software/cloud.md
  docs/software/dns_servers.md
  docs/software/social.md
  mkdocs.yml
Labels: release

#919 Typo
  docs/releases/v8_21.md
Labels: correction

#920 Clarify Rockchip kernel upgrade changelog entry
  docs/releases/v8_21.md
Labels: release
