Repository MichaIng/DietPi-Docs, pull requests merged in 2023-09, with the labels that each got.

#927 Add link to virtualizationhowto.com vSphere article
  docs/install.md
Labels: extension

#928 Update hardware.md
  docs/hardware.md
Labels: correction

#924 Add info about WiFi HotSpot combined with AdGuard Home resp. Pi-hole
  docs/software/advanced_networking.md
Labels: extension

#929 WiFi Hotspot: Added IP address comments to dhcpd.conf examples
  docs/software/advanced_networking.md
Labels: enhancement

#930 Release week 36
  .github/workflows/main.yml
  docs/hardware.md
  docs/install.md
  docs/releases/v6_27.md
  docs/software/advanced_networking.md
Labels: release

#923 Add information for the ADSB Feeder software
  .wordlist.txt
  docs/assets/images/ADSB-Feeder-Setup-Page.png
  docs/assets/images/TAR1090-view.png
  docs/software.md
  docs/software/distributed_projects.md
Labels: extension, Next DietPi release

#931 Releasenotes v8.22
  .wordlist.txt
  docs/assets/images/dietpi-release-v8_22.jpg
  docs/releases.md
  docs/releases/v6_30.md
  docs/releases/v8_22.md
  docs/software.md
  docs/software/gaming.md
  docs/software/media.md
  mkdocs.yml
Labels: release

#933 Release week 38
  .wordlist.txt
  docs/assets/images/ADSB-Feeder-Setup-Page.png
  docs/assets/images/TAR1090-view.png
  docs/assets/images/dietpi-release-v8_22.jpg
  docs/releases.md
  docs/releases/v6_30.md
  docs/releases/v8_22.md
  docs/software.md
  docs/software/distributed_projects.md
  docs/software/gaming.md
  docs/software/media.md
  mkdocs.yml
Labels: release

#934 Missing blank line
  docs/software/vpn.md
Labels: correction

#935 Adjustments for xz-compressed images
  docs/hardware.md
  docs/install.md
Labels: correction

#936 Release week 38.2
  docs/hardware.md
  docs/install.md
  docs/software/vpn.md
Labels: release

#939 Gitea/Gogs UDP port reference removed
  docs/software/cloud.md
Labels: correction
