Repository MichaIng/DietPi-Docs, pull requests merged in 2024-06, with the labels that each got.

#1007 ci: update and simplification
  .github/workflows/main.yml
Labels: CI

#1006 Release week 22
  .github/workflows/main.yml
  docs/hardware.md
  docs/install.md
  docs/software/camera.md
  docs/software/gaming.md
  docs/software/programming.md
  docs/software/webserver_stack.md
Labels: release

#1008 Documentation for Forgejo
  .wordlist.txt
  docs/assets/images/dietpi-software-cloud-forgejo.svg
  docs/hardware.md
  docs/software.md
  docs/software/cloud.md
Labels: extension

#1009 Releasenotes v9.5
  .wordlist.txt
  docs/assets/images/dietpi-VirtualBox-IPv6.png
  docs/assets/images/dietpi-release-v9_05.jpg
  docs/install.md
  docs/releases.md
  docs/releases/v9_3.md
  docs/releases/v9_4.md
  docs/releases/v9_5.md
  docs/software/media.md
  mkdocs.yml
Labels: release

#1010 Release week 24
  .wordlist.txt
  docs/assets/images/dietpi-VirtualBox-IPv6.png
  docs/assets/images/dietpi-release-v9_05.jpg
  docs/assets/images/dietpi-software-cloud-forgejo.svg
  docs/hardware.md
  docs/install.md
  docs/releases.md
  docs/releases/v9_3.md
  docs/releases/v9_4.md
  docs/releases/v9_5.md
  docs/software.md
  docs/software/cloud.md
  docs/software/media.md
  mkdocs.yml
Labels: release

#1012 Release photo description of Pi hardware added
  docs/releases/v9_0.md
  docs/releases/v9_1.md
  docs/releases/v9_2.md
  docs/releases/v9_3.md
  docs/releases/v9_4.md
  docs/releases/v9_5.md
Labels: extension
