Repository MichaIng/DietPi-Docs, pull requests merged in 2024-12, with the labels that each got.

#1039 Tomcat version added to installation description
  .github/workflows/main.yml
  docs/software/webserver_stack.md
Labels: enhancement

#1038 Proxmox installation docs updated to ISO file installation
  docs/assets/images/Proxmox_ISO-Upload1.png
  docs/assets/images/Proxmox_ISO-Upload2.png
  docs/assets/images/Proxmox_ISO-Upload3.png
  docs/assets/images/Proxmox_ISO-Upload4.png
  docs/assets/images/Proxmox_VM-generation-ISO.png
  docs/install.md
Labels: extension

#1037 DietPi-Software | frp
  docs/software/advanced_networking.md
Labels: enhancement, Next DietPi release

#1034 Update MineOS docs
  docs/software/gaming.md
Labels: Next DietPi release

#1040 Releasenotes v9.9 and new hardware variants
  .wordlist.txt
  docs/assets/images/dietpi-release-v9_09.jpg
  docs/hardware.md
  docs/releases.md
  docs/releases/v9_9.md
  docs/software/programming.md
  mkdocs.yml
Labels: release

#1041 Release week 52
  .github/workflows/main.yml
  .wordlist.txt
  docs/assets/images/Proxmox_ISO-Upload1.png
  docs/assets/images/Proxmox_ISO-Upload2.png
  docs/assets/images/Proxmox_ISO-Upload3.png
  docs/assets/images/Proxmox_ISO-Upload4.png
  docs/assets/images/Proxmox_VM-generation-ISO.png
  docs/assets/images/dietpi-release-v9_09.jpg
  docs/hardware.md
  docs/install.md
  docs/releases.md
  docs/releases/v9_9.md
  docs/software/advanced_networking.md
  docs/software/distributed_projects.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/programming.md
  docs/software/system_security.md
  docs/software/webserver_stack.md
  mkdocs.yml
Labels: release

#1043 Release date v9.9 corrected
  docs/releases/v9_9.md
Labels: correction

#1044 Release date v9.9 corrected (#1043)
  docs/releases/v9_9.md
Labels: correction

#1045 Renaming LMS to Lyrion Music Server
  docs/releases/v9_9.md
  docs/software.md
  docs/software/media.md
Labels: correction
