Repository MichaIng/DietPi-Docs, pull requests merged in 2024-01, with the labels that each got.

#963 Fix Update cmd for motionEye cmd
  docs/software/camera.md
Labels: correction

#964 DietPi-Hardware | add a hint for testing images.
  docs/hardware.md
Labels: enhancement

#965 Releasenotes v9.0
  docs/assets/images/dietpi-release-v9_00.jpg
  docs/hardware.md
  docs/releases.md
  docs/releases/v9_0.md
  mkdocs.yml
Labels: release

#966 Release week 3
  .wordlist.txt
  docs/assets/images/dietpi-release-v9_00.jpg
  docs/hardware.md
  docs/releases.md
  docs/releases/v8_25.md
  docs/releases/v9_0.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/file_servers.md
  docs/software/programming.md
  docs/software/social.md
  docs/usage.md
  mkdocs.yml
Labels: release

#967 Corrected release notes (short overview)
  docs/releases/v9_0.md
Labels: correction

#968 Some fixes
  docs/releases/v9_0.md
Labels: release

#969 fix(docs): Incorrect postgresql reload command
  docs/software/databases.md
Labels: correction
