Repository MichaIng/DietPi-Docs, pull requests merged in 2024-05, with the labels that each got.

#995 Extend Home Assistant docs and fix Gitea links
  docs/software/cloud.md
  docs/software/home_automation.md
  docs/software/webserver_stack.md
Labels: correction, extension

#996 DietPi v9.4 release
  .wordlist.txt
  docs/assets/images/dietpi-release-v9_04.jpg
  docs/hardware.md
  docs/releases.md
  docs/releases/v9_4.md
  docs/software/webserver_stack.md
  mkdocs.yml
Labels: Next DietPi release

#997 Release week 19
  .wordlist.txt
  docs/assets/images/dietpi-release-v9_04.jpg
  docs/hardware.md
  docs/releases.md
  docs/releases/v9_4.md
  docs/software/cloud.md
  docs/software/home_automation.md
  docs/software/remote_desktop.md
  docs/software/webserver_stack.md
  docs/usage.md
  mkdocs.yml
Labels: release

#999 Move images out of testing
  docs/hardware.md
Labels: correction

#1001 Update v9_4.md: Corrected listing of new hardware support (#1000)
  docs/releases/v9_4.md
Labels: correction, release

#1003 Typo
  .github/workflows/main.yml
  docs/hardware.md
  docs/software/camera.md
  docs/software/gaming.md
Labels: correction

#1005 Description of making docker-data/tmp a tmpfs
  docs/software/programming.md
Labels: extension

#1004 Docker: Add short info about other available plugins
  docs/software/programming.md
  docs/software/webserver_stack.md
Labels: extension
