Repository MichaIng/DietPi-Docs, pull requests merged in 2024-07, with the labels that each got.

#1014 Update Node-RED update info
  docs/software/hardware_projects.md
Labels: correction

#1013 software/social: added soju IRC bouncer
  .github/workflows/main.yml
  .wordlist.txt
  docs/software.md
  docs/software/social.md
Labels: extension

#1015 Deprecated :octicons-commit-24: replaced by |
  docs/releases/v6_28.md
  docs/releases/v6_32.md
  docs/releases/v6_33.md
Labels: correction

#1018 Releasenotes v9.6
  .wordlist.txt
  docs/assets/images/dietpi-release-v9_06.jpg
  docs/releases.md
  docs/releases/v7_0.md
  docs/releases/v9_4.md
  docs/releases/v9_5.md
  docs/releases/v9_6.md
  mkdocs.yml
Labels: release

#1019 Release week 27
  .github/workflows/main.yml
  .wordlist.txt
  docs/assets/images/dietpi-release-v9_05.jpg
  docs/assets/images/dietpi-release-v9_06.jpg
  docs/assets/images/dietpi-software-cloud-forgejo.svg
  docs/releases.md
  docs/releases/v6_28.md
  docs/releases/v6_32.md
  docs/releases/v6_33.md
  docs/releases/v7_0.md
  docs/releases/v9_0.md
  docs/releases/v9_1.md
  docs/releases/v9_2.md
  docs/releases/v9_3.md
  docs/releases/v9_4.md
  docs/releases/v9_5.md
  docs/releases/v9_6.md
  docs/software.md
  docs/software/hardware_projects.md
  docs/software/social.md
  mkdocs.yml
Labels: release

#1020 Fix typo
  docs/releases/v9_6.md
Labels: correction

#1021 Backwards merge master > dev
  docs/releases/v9_6.md
Labels: meta
