Repository MichaIng/DietPi-Docs, pull requests merged in 2025-01, with the labels that each got.

#1046 VM hardware requirements described, image download links corrected
  docs/hardware.md
  docs/install.md
  docs/software/media.md
Labels: enhancement

#1047 Release week 1
  .github/workflows/main.yml
  docs/hardware.md
  docs/install.md
  docs/releases/v9_9.md
  docs/software.md
  docs/software/media.md
Labels: release

#1048 Added information for QEMU Guest Agent activation
  .wordlist.txt
  docs/install.md
Labels: enhancement

#1051 NFS-Server: Usage of macOS mounts described, graphics load optimized, link correction
  docs/assets/images/dietpi-software-fileserver-macos_permanent_nfs_mount.jpg
  docs/install.md
  docs/software/file_servers.md
Labels: extension

#1053 Description of Samba password extended, link corrections
  docs/references.md
  docs/software/file_servers.md
  docs/software/programming.md
Labels: extension

#1055 Missing CR/LF leads to wrong shell command display
  docs/releases/v8_0.md
  docs/software/cloud.md
Labels: correction
