Repository MichaIng/DietPi-Docs, pull requests merged in 2025-02, with the labels that each got.

#1057 Doc for Midnight Commander (`mc`) added
  docs/assets/images/dietpi-software-systemstat-midnightcommander.png
  docs/releases/v8_24.md
  docs/software.md
  docs/software/system_stats.md
Labels: extension

#1056 Software title grouping adjusted to dietpi-software
  .github/workflows/main.yml
  docs/software.md
  docs/software/programming.md
  docs/software/system_stats.md
  docs/software/webserver_stack.md
Labels: correction

#1050 Links to RISC-V changed from Sid to Trixie
  docs/hardware.md
Labels: correction, Next DietPi release

#1058 Releasenotes V9.10, new dietpi.txt option and new dietpi-display command
  docs/assets/images/dietpi-tools-dietpidisplay.png
  docs/dietpi_tools.md
  docs/dietpi_tools/system_configuration.md
  docs/releases.md
  docs/releases/v9_10.md
  docs/usage.md
  mkdocs.yml
Labels: release

#1060 Release week 6
  .github/workflows/main.yml
  .wordlist.txt
  docs/assets/images/Proxmox_ISO-Upload1.png
  docs/assets/images/Proxmox_ISO-Upload2.png
  docs/assets/images/Proxmox_ISO-Upload3.png
  docs/assets/images/Proxmox_ISO-Upload4.png
  docs/assets/images/Proxmox_VM-generation-ISO.png
  docs/assets/images/dietpi-release-v9_08.jpg
  docs/assets/images/dietpi-release-v9_09.jpg
  docs/assets/images/dietpi-release-v9_10.webp
  docs/assets/images/dietpi-software-advanced-networking-avahi-logo.png
  docs/assets/images/dietpi-software-fileserver-macos_permanent_nfs_mount.jpg
  docs/assets/images/dietpi-software-systemstat-midnightcommander.png
  docs/assets/images/dietpi-tools-dietpidisplay.png
  docs/dietpi_tools.md
  docs/dietpi_tools/system_configuration.md
  docs/hardware.md
  docs/install.md
  docs/references.md
  docs/releases.md
  docs/releases/v7_8.md
  docs/releases/v8_0.md
  docs/releases/v8_24.md
  docs/releases/v9_0.md
  docs/releases/v9_10.md
  docs/releases/v9_3.md
  docs/software.md
  docs/software/advanced_networking.md
  docs/software/cloud.md
  docs/software/file_servers.md
  docs/software/media.md
  docs/software/programming.md
  docs/software/system_stats.md
  docs/software/webserver_stack.md
  docs/usage.md
  mkdocs.yml
Labels: release

#1062 Update Raspberry Pi downloads
  docs/hardware.md
Labels: release

#1064 Correct graphics alt attribute (#1063)
  docs/releases/v9_10.md
Labels: release

#1065 Add social media images for release notes
  docs/index.md
  docs/releases/v9_10.md
  mkdocs.yml
  overrides/main.html
Labels: enhancement

#1067 Add DietPi v9.11 release notes
  docs/assets/images/dietpi-release-v9_11.webp
  docs/index.md
  docs/releases.md
  docs/releases/v6_34.md
  docs/releases/v7_0.md
  docs/releases/v7_1.md
  docs/releases/v7_2.md
  docs/releases/v8_0.md
  docs/releases/v8_1.md
  docs/releases/v8_13.md
  docs/releases/v8_14.md
  docs/releases/v8_15.md
  docs/releases/v8_16.md
  docs/releases/v8_2.md
  docs/releases/v8_22.md
  docs/releases/v8_25.md
  docs/releases/v9_11.md
  docs/releases/v9_8.md
  docs/releases/v9_9.md
  docs/software/camera.md
  mkdocs.yml
Labels: release

#1068 Update Pi-hole docs for v6
  docs/software/dns_servers.md
Labels: correction

#1070 Pi-hole screenshot update to v6
  docs/assets/images/dietpi-software-dnsserver-pihole.png
  docs/software/dns_servers.md
  docs/software/webserver_stack.md
Labels: enhancement
