Repository MichaIng/DietPi-Docs, pull requests merged in 2025-09, with the labels that each got.

#1107 Releasenotes v9.17
  .wordlist.txt
  docs/hardware.md
  docs/releases.md
  docs/releases/v7_1.md
  docs/releases/v7_5.md
  docs/releases/v7_8.md
  docs/releases/v8_22.md
  docs/releases/v8_24.md
  docs/releases/v8_3.md
  docs/releases/v8_5.md
  docs/releases/v9_17.md
  docs/releases/v9_2.md
  docs/software.md
  docs/software/media.md
  mkdocs.yml
Labels: release

#1108 Release week 38
  .github/workflows/main.yml
  .wordlist.txt
  docs/assets/images/dietpi-release-v9_17.webp
  docs/hardware.md
  docs/releases.md
  docs/releases/v6_34.md
  docs/releases/v7_1.md
  docs/releases/v7_5.md
  docs/releases/v7_8.md
  docs/releases/v8_17.md
  docs/releases/v8_2.md
  docs/releases/v8_22.md
  docs/releases/v8_24.md
  docs/releases/v8_3.md
  docs/releases/v8_5.md
  docs/releases/v8_7.md
  docs/releases/v8_9.md
  docs/releases/v9_10.md
  docs/releases/v9_12.md
  docs/releases/v9_17.md
  docs/releases/v9_2.md
  docs/releases/v9_4.md
  docs/releases/v9_5.md
  docs/releases/v9_6.md
  docs/releases/v9_7.md
  docs/software.md
  docs/software/media.md
  docs/software/system_stats.md
  docs/usage.md
  mkdocs.yml
Labels: release

#1109 Spelling correction
  docs/releases/v9_17.md
Labels: correction

#1110 Add SSH server public keys and set SSH server login options
  docs/software/ssh.md
Labels: extension

#1113 Use snippet for software info box
  docs/software/advanced_networking.md
  docs/software/bittorrent.md
  docs/software/camera.md
  docs/software/cloud.md
  docs/software/databases.md
  docs/software/desktop.md
  docs/software/distributed_projects.md
  docs/software/dns_servers.md
  docs/software/file_servers.md
  docs/software/gaming.md
  docs/software/hardware_projects.md
  docs/software/home_automation.md
  docs/software/log_system.md
  docs/software/media.md
  docs/software/printing.md
  docs/software/programming.md
  docs/software/remote_desktop.md
  docs/software/social.md
  docs/software/ssh.md
  docs/software/system_security.md
  docs/software/system_software.md
  docs/software/system_stats.md
  docs/software/vpn.md
  docs/software/webserver_stack.md
  mkdocs.yml
  snippet-includes/DietPi-Software_infoblock.md
Labels: enhancement
