Repository MichaIng/DietPi-Docs, pull requests merged in 2025-07, with the labels that each got.

#1091 Add dietpi homer-theme
  docs/software/system_stats.md
Labels: extension

#1093 Re structure homer themes
  docs/assets/images/homer-preview.png
  docs/software/system_stats.md
Labels: enhancement

#1095 Add DietPi v9.15 release notes
  docs/assets/images/dietpi-release-v9_15.webp
  docs/releases.md
  docs/releases/v9_15.md
  mkdocs.yml
Labels: Next DietPi release

#1094 Release week 31
  .github/workflows/main.yml
  docs/assets/images/dietpi-release-v9_15.webp
  docs/assets/images/homer-preview.png
  docs/hardware.md
  docs/releases.md
  docs/releases/v9_15.md
  docs/software/cloud.md
  docs/software/databases.md
  docs/software/system_stats.md
  mkdocs.yml
Labels: release

#1074 Add documentation about command line options of the DietPi tools
  docs/dietpi_tools/misc_tools.md
  docs/dietpi_tools/software_installation.md
  docs/dietpi_tools/system_configuration.md
  docs/dietpi_tools/system_maintenance.md
Labels: extension
